window.REVOLUTION_CHARACTER_RELATIONS = {
  groups: {
    clergy: { label: "Духовенство", color: "#517648" },
    court: { label: "Двор и роялисты", color: "#8f4a2f" },
    military: { label: "Армия", color: "#5b495e" },
    politicians: { label: "Депутаты и клубы", color: "#205b8f" },
    press: { label: "Печать и слухи", color: "#a84d6f" },
    repression: { label: "Комитеты и репрессии", color: "#3f424a" },
    market: { label: "Рынок и мастерские", color: "#9b6a1a" },
    poor: { label: "Городские низы", color: "#a33d2e" }
  },
  domains: {
    food: { label: "Хлеб", color: "#a33d2e" },
    economy: { label: "Деньги", color: "#9b6a1a" },
    work: { label: "Работа", color: "#1f6f78" },
    politics: { label: "Политика", color: "#205b8f" },
    religion: { label: "Церковь", color: "#517648" },
    war: { label: "Война", color: "#5b495e" },
    street: { label: "Улица", color: "#a84d6f" },
    repression: { label: "Подозрение", color: "#3f424a" },
    provinces: { label: "Провинции", color: "#2f7d7e" }
  },
  characters: [
    { id: "sieyes", name: "Сийес", group: "clergy", resources: ["COIN", "RIGHT", "WORK"], risks: ["потеря церковной базы"] },
    { id: "talleyrand", name: "Талейран", group: "clergy", resources: ["COIN", "PROPERTY", "RIGHT"], risks: ["конфискация", "переключение режима"] },
    { id: "maury", name: "Аббат Мори", group: "clergy", resources: ["COIN", "RIGHT", "SUSPICION"], risks: ["эмиграция", "арест"] },
    { id: "cure", name: "Кюре", group: "clergy", resources: ["OATH", "WORK", "BREAD"], risks: ["раскол прихода", "неприсяга"] },
    { id: "lafayette", name: "Лафайет", group: "military", resources: ["PROPERTY", "SOLDIER"], risks: ["улица", "порядок против свободы"] },
    { id: "louis_xvi", name: "Людовик XVI", group: "court", resources: ["COIN", "PROPERTY", "DEBT"], risks: ["казна", "вето", "подозрение"] },
    { id: "marie_antoinette", name: "Мария-Антуанетта", group: "court", resources: ["COIN", "RIGHT", "SUSPICION"], risks: ["слухи", "двор дорогой"] },
    { id: "artois", name: "Артуа", group: "court", resources: ["COIN", "PROPERTY", "RIGHT"], risks: ["эмиграция", "конфискация"] },
    { id: "provence", name: "Прованский", group: "court", resources: ["COIN", "PROPERTY", "RIGHT"], risks: ["эмиграция", "торг с новым режимом"] },
    { id: "polignac", name: "Полиньяк", group: "court", resources: ["COIN", "RIGHT", "PROPERTY"], risks: ["пенсии", "эмиграция"] },
    { id: "lamballe", name: "Ламбаль", group: "court", resources: ["COIN", "RIGHT", "SUSPICION"], risks: ["двор", "толпа"] },
    { id: "fersen", name: "Ферзен", group: "court", resources: ["COIN", "SOLDIER", "PROPERTY"], risks: ["иностранная связь", "бегство"] },
    { id: "mirabeau", name: "Мирабо", group: "politicians", resources: ["PROPERTY", "DEBT", "WORK"], risks: ["продажа влияния"] },
    { id: "charlotte_corday", name: "Шарлотта Корде", group: "court", resources: ["PROPERTY", "SUSPICION"], risks: ["провинция", "радикалы"] },
    { id: "barras", name: "Баррас", group: "politicians", resources: ["PROPERTY", "WORK"], risks: ["смена режима"] },
    { id: "cazales", name: "Казалес", group: "court", resources: ["RIGHT", "SOLDIER"], risks: ["отмена прав", "эмиграция"] },
    { id: "dumouriez", name: "Дюмурье", group: "military", resources: ["SOLDIER", "WORK"], risks: ["измена", "поражение"] },
    { id: "napoleon", name: "Наполеон", group: "military", resources: ["SOLDIER", "WORK"], risks: ["бедность без войны"] },
    { id: "buonarroti", name: "Буонарроти", group: "politicians", resources: ["PROPERTY", "WORK"], risks: ["подполье", "подозрение"] },
    { id: "breteuil", name: "Бретёй", group: "court", resources: ["RIGHT", "SUSPICION"], risks: ["падение двора"] },
    { id: "bouille", name: "Буйе", group: "military", resources: ["SOLDIER", "PROPERTY"], risks: ["заговор", "эмиграция"] },
    { id: "necker", name: "Неккер", group: "market", resources: ["COIN", "DUE", "WORK"], risks: ["доверие к казне"] },
    { id: "bailly", name: "Байи", group: "politicians", resources: ["WORK", "муниципалитет"], risks: ["толпа", "порядок"] },
    { id: "barnave", name: "Барнав", group: "politicians", resources: ["WORK", "речь"], risks: ["компромисс под подозрением"] },
    { id: "marat", name: "Марат", group: "press", resources: ["WORK", "LEAFLET"], risks: ["конфликт", "подозрение"] },
    { id: "robespierre", name: "Робеспьер", group: "politicians", resources: ["WORK", "клуб"], risks: ["логика подозрения"] },
    { id: "brissot", name: "Бриссо", group: "press", resources: ["WORK", "газета"], risks: ["война", "поражение"] },
    { id: "roland", name: "Ролан", group: "politicians", resources: ["WORK", "PROPERTY"], risks: ["ассигнаты", "фракция"] },
    { id: "manon_roland", name: "Манон Ролан", group: "politicians", resources: ["WORK", "салон"], risks: ["чистка"] },
    { id: "vergniaud", name: "Верньо", group: "politicians", resources: ["WORK", "речь"], risks: ["фракционная принадлежность"] },
    { id: "danton", name: "Дантон", group: "politicians", resources: ["WORK", "DUE"], risks: ["обвинение в продажности"] },
    { id: "saint_just", name: "Сен-Жюст", group: "politicians", resources: ["WORK", "комитет"], risks: ["жесткость"] },
    { id: "hebert", name: "Эбер", group: "press", resources: ["WORK", "LEAFLET"], risks: ["откат", "подозрение"] },
    { id: "couthon", name: "Кутон", group: "politicians", resources: ["WORK", "комитет"], risks: ["террор"] },
    { id: "desmoulins", name: "Демулен", group: "press", resources: ["WORK", "памфлет"], risks: ["слово становится уликой"] },
    { id: "carnot", name: "Карно", group: "military", resources: ["WORK", "SOLDIER"], risks: ["снабжение", "война"] },
    { id: "barere", name: "Барер", group: "politicians", resources: ["WORK", "комитет"], risks: ["ответственность большинства"] },
    { id: "fouquier_tinville", name: "Фукье-Тенвиль", group: "repression", resources: ["WORK", "SUSPICION"], risks: ["откат"] },
    { id: "carrier", name: "Каррье", group: "repression", resources: ["WORK", "SUSPICION"], risks: ["провинциальная злость"] },
    { id: "fouche", name: "Фуше", group: "repression", resources: ["WORK", "SUSPICION"], risks: ["списки", "смена режима"] },
    { id: "tallien", name: "Тальен", group: "politicians", resources: ["WORK", "сеть"], risks: ["Термидор", "безопасность"] },
    { id: "babeuf", name: "Бабёф", group: "press", resources: ["WORK", "SUSPICION"], risks: ["бедность", "передел"] },
    { id: "moreau", name: "Моро", group: "military", resources: ["SOLDIER", "WORK"], risks: ["лояльность"] },
    { id: "larevelliere", name: "Ларевельер-Лепо", group: "politicians", resources: ["WORK", "идеология"], risks: ["религиозная политика"] },
    { id: "avocat", name: "Адвокат Меренвиль", group: "politicians", resources: ["WORK"], risks: ["клиенты", "радикализация"] },
    { id: "chirurgien", name: "Хирург", group: "market", resources: ["WORK", "MEDICINE"], risks: ["оплата больницы"] },
    { id: "poissarde", name: "Торговка", group: "poor", resources: ["PROPERTY", "WORK"], risks: ["Максимум", "рынок"] },
    { id: "vinier", name: "Откупщик Бертье", group: "market", resources: ["COIN", "TAX_DUE", "RIGHT"], risks: ["стена", "погром", "памфлет"] },
    { id: "cafetier", name: "Хозяин кафе", group: "market", resources: ["PROPERTY", "WORK"], risks: ["слухи", "клиенты"] },
    { id: "mercier", name: "Лавочник", group: "market", resources: ["PROPERTY", "DEBT"], risks: ["обыск", "Максимум"] },
    { id: "boulanger", name: "Булочник", group: "market", resources: ["BREAD", "GRAIN", "WORK"], risks: ["голодная очередь"] },
    { id: "menuisier", name: "Столяр", group: "market", resources: ["PROPERTY", "WORK"], risks: ["нет заказа"] },
    { id: "imprimeur", name: "Типограф", group: "press", resources: ["PROPERTY", "PAPER", "WORK"], risks: ["цензура", "подозрение"] },
    { id: "pichegru", name: "Пишегрю", group: "military", resources: ["SOLDIER", "WORK"], risks: ["роялистские связи"] },
    { id: "jourdan", name: "Журдан", group: "military", resources: ["SOLDIER", "WORK"], risks: ["рекрутчина"] },
    { id: "lavandiere", name: "Прачка", group: "poor", resources: ["WORK", "BREAD_NEED"], risks: ["голод", "потеря работы"] },
    { id: "actrice", name: "Актриса", group: "poor", resources: ["WORK"], risks: ["цензура", "публика"] },
    { id: "invalide", name: "Солдат-инвалид", group: "poor", resources: ["SOLDIER", "PROPERTY"], risks: ["пенсия", "оружие"] },
    { id: "journalier", name: "Подёнщик", group: "poor", resources: ["WORK", "BREAD_NEED"], risks: ["первый голод"] },
    { id: "servante", name: "Служанка", group: "poor", resources: ["WORK", "слухи"], risks: ["хозяин исчез"] }
  ],
  relations: [
    {
      id: "bread_flow",
      title: "Хлебная цепочка",
      domain: "food",
      stage: "source",
      x: 13,
      y: 28,
      summary: "Зерно становится хлебом, хлеб становится голодом или политическим требованием.",
      participants: ["boulanger", "poissarde", "vinier", "mercier", "journalier", "lavandiere", "servante", "invalide", "cure", "marat", "hebert", "desmoulins", "imprimeur"],
      npc: ["провинция-зерно", "перевозчик", "налоговая стена"],
      gives: "зерно, хлеб, деньги, очередь, помощь",
      takes: "монету/ассигнаты, труд, доверие, спокойствие",
      playerLevers: ["купить хлеб", "купить зерно и нанять обоз", "спрятать зерно", "открыть склад", "собрать хлебный марш"],
      masterLevers: ["цена хлеба", "пришло зерна", "хватает ли булочнику зерна", "сколько голодных", "черный рынок"],
      opens: ["голод", "слух", "марш", "бунт", "Максимум"]
    },
    {
      id: "tax_wall",
      title: "Налоговая стена",
      domain: "economy",
      stage: "exchange",
      x: 34,
      y: 17,
      summary: "Пошлина делает налог видимым врагом и связывает откупщика, торговцев, городскую цену и толпу.",
      participants: ["vinier", "poissarde", "mercier", "boulanger", "necker", "louis_xvi", "bailly"],
      npc: ["сборщик", "перевозчик", "городские ворота"],
      gives: "печать прохода, доход казны, повод для ненависти",
      takes: "пошлину, время, легальность груза",
      playerLevers: ["заплатить", "контрабандить", "сжечь заставу", "требовать отмены"],
      masterLevers: ["вклад пошлины в цену", "риск задержки", "рост контрабанды"],
      opens: ["контрабанда", "погром застав", "налоговый спор"]
    },
    {
      id: "work_wages",
      title: "Работа и жалованье",
      domain: "work",
      stage: "source",
      x: 12,
      y: 57,
      summary: "Работа соединяет бедных с мастерскими, государством, армией и богатыми домами.",
      participants: ["menuisier", "imprimeur", "boulanger", "mercier", "cafetier", "lavandiere", "servante", "journalier", "actrice", "chirurgien", "roland", "lamballe", "polignac"],
      npc: ["биржа труда", "частный наниматель", "Контора"],
      gives: "карточку работы, оплату, хлеб, зависимость",
      takes: "труд, время, лояльность, риск невыплаты",
      playerLevers: ["нанять", "искать работу", "задержать оплату", "потребовать долг"],
      masterLevers: ["сколько открытых работ", "какие выплаты задержаны", "работает ли мастерская"],
      opens: ["долг", "безработица", "секционное давление", "армия как выход"]
    },
    {
      id: "debt_credit",
      title: "Долг и кредит",
      domain: "economy",
      stage: "exchange",
      x: 35,
      y: 38,
      summary: "Долг превращает богатого в покровителя, бедного в зависимого, а государство в заложника доверия.",
      participants: ["necker", "louis_xvi", "mirabeau", "danton", "mercier", "cafetier", "journalier", "lavandiere", "servante", "invalide"],
      npc: ["казна", "кредиторы", "нотариус"],
      gives: "монету, отсрочку, расписку, политическое время",
      takes: "проценты, услугу, голос, имущество в залог",
      playerLevers: ["дать заем", "взять долг", "простить долг", "потребовать выплату"],
      masterLevers: ["доверие к казне", "невыплаты", "банкротство"],
      opens: ["зависимость", "продажа имущества", "политическая сделка"]
    },
    {
      id: "assignats",
      title: "Ассигнаты",
      domain: "economy",
      stage: "exchange",
      x: 37,
      y: 65,
      summary: "Бумага решает платеж сегодня, но бьет по тем, кто получает фиксированный доход.",
      participants: ["necker", "louis_xvi", "roland", "fouquier_tinville", "carrier", "fouche", "mercier", "vinier", "boulanger", "poissarde", "journalier", "lavandiere", "servante", "cure", "invalide"],
      npc: ["казна", "типография денег", "рынок"],
      gives: "жалованье, эмиссию, номинальные деньги",
      takes: "доверие, покупательную силу, монету из оборота",
      playerLevers: ["принять бумагу", "отказаться", "менять на монету", "печатать новую серию"],
      masterLevers: ["курс ассигната", "отказы принимать", "масса бумаги"],
      opens: ["инфляция", "черный рынок", "невыплаты", "обвал доверия"]
    },
    {
      id: "property_biens",
      title: "Собственность и биены",
      domain: "economy",
      stage: "exchange",
      x: 39,
      y: 87,
      summary: "Старое имущество переходит через конфискацию и аукцион в новую элиту.",
      participants: ["sieyes", "talleyrand", "maury", "artois", "polignac", "lamballe", "fersen", "breteuil", "bouille", "cazales", "louis_xvi", "marie_antoinette", "necker", "barras", "tallien", "fouche", "mercier", "cafetier", "menuisier"],
      npc: ["аукционист", "конфискат", "биены"],
      gives: "имущество, доход, залог под бумагу",
      takes: "старое право, безопасность владельца, монету/ассигнаты покупателя",
      playerLevers: ["эмигрировать", "конфисковать", "купить биен", "заложить имущество"],
      masterLevers: ["какие лоты доступны", "курс ассигната при продаже", "основание конфискации"],
      opens: ["новая элита", "ненависть к покупателям", "судьба эмигрантов"]
    },
    {
      id: "church_oath",
      title: "Церковь и присяга",
      domain: "religion",
      stage: "pressure",
      x: 61,
      y: 23,
      summary: "Государство получает ресурс, но ломает доверие прихода и запускает раскол совести.",
      participants: ["cure", "sieyes", "talleyrand", "maury", "larevelliere", "hebert", "fouche", "carrier", "saint_just", "robespierre"],
      npc: ["приход", "неприсягнувшие", "провинция"],
      gives: "жалованье, помощь бедным, легитимность, подпольную поддержку",
      takes: "церковную землю, автономию, доверие прихода",
      playerLevers: ["присягнуть", "отказаться", "прятать фонд", "настроить приход"],
      masterLevers: ["религиозный раскол", "лояльность провинций", "риск Вандеи"],
      opens: ["неприсяга", "тайная церковь", "провинциальный мятеж"]
    },
    {
      id: "representation_law",
      title: "Представительство и закон",
      domain: "politics",
      stage: "pressure",
      x: 61,
      y: 43,
      summary: "Речь, голосование и печать превращают частный кризис в декрет.",
      participants: ["bailly", "barnave", "mirabeau", "sieyes", "louis_xvi", "lafayette", "necker", "vergniaud", "roland", "manon_roland", "brissot", "danton", "robespierre"],
      npc: ["Ассамблея", "комитет", "королевское вето"],
      gives: "декрет, процедуру, мандат, новую законность",
      takes: "подписи, голоса, политический риск, время",
      playerLevers: ["писать декрет", "искать голоса", "наложить вето", "давить через клуб"],
      masterLevers: ["побочные эффекты декрета", "затяжка", "ответ улицы"],
      opens: ["новое правило", "раскол фракций", "улица против процедуры"]
    },
    {
      id: "press_rumor",
      title: "Печать, кафе и слух",
      domain: "street",
      stage: "pressure",
      x: 63,
      y: 63,
      summary: "Слово дает боли виновника: спекулянт, король, священник, изменник, Париж.",
      participants: ["marat", "hebert", "desmoulins", "brissot", "imprimeur", "cafetier", "manon_roland", "babeuf", "poissarde"],
      npc: ["газета", "кафе", "рынок", "клуб"],
      gives: "листовку, слух, обвинение, подписи",
      takes: "бумагу, деньги, репутацию цели, риск цензуры",
      playerLevers: ["напечатать", "распространить", "обвинить", "дать контрпамфлет"],
      masterLevers: ["скорость распространения", "паника", "риск насилия"],
      opens: ["толпа", "донос", "петиция", "погром"]
    },
    {
      id: "street_mobilization",
      title: "Улица и секции",
      domain: "street",
      stage: "outcome",
      x: 84,
      y: 27,
      summary: "Голод, слух и организация становятся физическим давлением на власть.",
      participants: ["poissarde", "journalier", "lavandiere", "servante", "invalide", "marat", "hebert", "danton", "desmoulins", "bailly", "lafayette"],
      npc: ["секция", "толпа", "гвардия"],
      gives: "число людей, требование, угрозу, защиту",
      takes: "хлеб, уступку, арест лидеров, риск насилия",
      playerLevers: ["собрать марш", "подать петицию", "штурмовать", "разойтись"],
      masterLevers: ["порог массового действия", "ответ гвардии", "цена уступки"],
      opens: ["уступка", "подавление", "радикализация", "новый декрет"]
    },
    {
      id: "suspicion_terror",
      title: "Подозрение и Террор",
      domain: "repression",
      stage: "outcome",
      x: 86,
      y: 50,
      summary: "Политический оппонент становится угрозой, а имущество и свобода становятся ставкой.",
      participants: ["robespierre", "saint_just", "couthon", "barere", "fouquier_tinville", "fouche", "carrier", "tallien", "maury", "artois", "breteuil", "bouille", "cazales", "charlotte_corday", "marie_antoinette", "louis_xvi"],
      npc: ["комитет", "трибунал", "реестр подозрительных"],
      gives: "черную метку, ордер, конфискацию, страх",
      takes: "свободу, должность, имущество, право голоса",
      playerLevers: ["донести", "снять подозрение", "выдать ордер", "защитить обвиняемого"],
      masterLevers: ["легкость обвинения", "скорость ареста", "усталость от страха"],
      opens: ["арест", "конфискация", "Термидор", "самострах элит"]
    },
    {
      id: "army_war",
      title: "Армия и война",
      domain: "war",
      stage: "source",
      x: 14,
      y: 84,
      summary: "Война дает карьеру и власть, но требует денег, людей, хлеба и материалов.",
      participants: ["lafayette", "dumouriez", "napoleon", "bouille", "fersen", "jourdan", "pichegru", "moreau", "carnot", "carrier", "saint_just", "invalide", "journalier", "servante"],
      npc: ["фронт", "армейский стол", "рекрутская квота"],
      gives: "жалованье, статус, заказ, вооруженную силу",
      takes: "людей, казну, зерно, ткань, лояльность",
      playerLevers: ["пойти добровольцем", "командовать", "дать подряд", "саботировать"],
      masterLevers: ["интенсивность войны", "поражения", "финансирование армии"],
      opens: ["рекрутчина", "поставки", "военный престиж", "переворот"]
    },
    {
      id: "requisitions",
      title: "Реквизиции",
      domain: "war",
      stage: "pressure",
      x: 62,
      y: 83,
      summary: "Центр получает ресурс сейчас и производит деревенскую злость на потом.",
      participants: ["carrier", "saint_just", "carnot", "jourdan", "napoleon", "boulanger", "menuisier", "vinier", "mercier", "cure"],
      npc: ["комиссар", "деревня", "склад", "армия"],
      gives: "зерно, лошадей, ткань, металл, снабжение фронта",
      takes: "доверие провинции, товар с рынка, безопасность реквизитора",
      playerLevers: ["реквизировать", "прятать", "компенсировать", "спорить о норме"],
      masterLevers: ["жесткость нормы", "срыв снабжения", "деревенское напряжение"],
      opens: ["Вандея", "партизанщина", "успех фронта", "черный рынок"]
    },
    {
      id: "vendee_province",
      title: "Вандея и провинция",
      domain: "provinces",
      stage: "outcome",
      x: 87,
      y: 75,
      summary: "Присяга, рекрутчина и реквизиции сходятся в сопротивление Парижу.",
      participants: ["cure", "maury", "carrier", "saint_just", "carnot", "charlotte_corday", "cazales", "bouille", "artois", "provence"],
      npc: ["Вандея", "приход", "местные дворяне", "уклонисты"],
      gives: "мятеж, укрытие, локальную лояльность",
      takes: "налоги, рекрутов, поставки, контроль центра",
      playerLevers: ["созвать сход", "благословить сопротивление", "подавить", "дать уступку"],
      masterLevers: ["порог мятежа", "масштаб внутреннего фронта", "жесткость подавления"],
      opens: ["внутренний фронт", "террор", "федерализм", "армейское подавление"]
    },
    {
      id: "patronage_secrets",
      title: "Покровительство и сведения",
      domain: "politics",
      stage: "exchange",
      x: 37,
      y: 51,
      summary: "Слуги, салоны, кафе и операторы режима меняют сведения на хлеб, защиту и безопасность.",
      participants: ["servante", "lamballe", "marie_antoinette", "polignac", "cafetier", "manon_roland", "danton", "mirabeau", "barras", "tallien", "fouche"],
      npc: ["салон", "дом", "кафе", "полицейская сеть"],
      gives: "информацию, протекцию, убежище, доступ",
      takes: "лояльность, молчание, деньги, риск доноса",
      playerLevers: ["нанять", "выдать слух", "спрятать", "предать покровителя"],
      masterLevers: ["ценность информации", "риск раскрытия", "защита от подозрения"],
      opens: ["шантаж", "спасение", "донос", "смена стороны"]
    },
    {
      id: "faction_club",
      title: "Клубы и фракции",
      domain: "politics",
      stage: "pressure",
      x: 61,
      y: 54,
      summary: "Фракция собирает людей, язык и дисциплину голосования, а затем становится мишенью.",
      participants: ["robespierre", "danton", "desmoulins", "marat", "hebert", "brissot", "vergniaud", "roland", "manon_roland", "barnave", "bailly", "tallien", "barras", "babeuf", "buonarroti"],
      npc: ["клуб", "секция", "комитет"],
      gives: "голоса, защиту, повестку, массовый канал",
      takes: "дисциплину, компромисс, риск чистки",
      playerLevers: ["создать коалицию", "исключить", "поддержать декрет", "обвинить фракцию"],
      masterLevers: ["раскол большинства", "цена проигрыша", "усталость от радикализма"],
      opens: ["чистка", "Термидор", "новая конституция", "подполье"]
    },
    {
      id: "black_market",
      title: "Черный рынок",
      domain: "economy",
      stage: "outcome",
      x: 85,
      y: 90,
      summary: "Ограничение цены без поставок уводит хлеб, монету и товар в тень.",
      participants: ["mercier", "vinier", "boulanger", "poissarde", "cafetier", "necker", "barras", "tallien", "fouche", "lavandiere", "journalier"],
      npc: ["спекулянт", "облава", "тайник"],
      gives: "товар, монету, кабальный курс, риск",
      takes: "легальность, доверие рынка, доступ бедных к хлебу",
      playerLevers: ["продать тайно", "купить сверх Максимума", "донести", "устроить облаву"],
      masterLevers: ["скрытая цена", "вероятность облавы", "дефицит легального рынка"],
      opens: ["подозрение", "обогащение", "погром лавки", "отказ от бумаги"]
    },
    {
      id: "medicine_aid",
      title: "Помощь и лечение",
      domain: "work",
      stage: "exchange",
      x: 35,
      y: 76,
      summary: "Голод и болезнь связывают бедных с церковью, врачом, соседями и покровителями.",
      participants: ["chirurgien", "cure", "lavandiere", "servante", "journalier", "invalide", "poissarde", "lamballe", "marie_antoinette"],
      npc: ["церковный фонд", "госпиталь", "соседи"],
      gives: "хлеб, лекарство, снятие метки, доверие",
      takes: "фонд, деньги, зависимость, репутационный риск",
      playerLevers: ["помочь", "отказать", "собрать фонд", "лечить за плату"],
      masterLevers: ["массовый голод", "болезнь", "доверие к церкви/секции"],
      opens: ["покровительство", "злость обойденных", "рост доверия"]
    }
  ],
  links: [
    ["bread_flow", "press_rumor"],
    ["bread_flow", "street_mobilization"],
    ["bread_flow", "black_market"],
    ["tax_wall", "bread_flow"],
    ["tax_wall", "black_market"],
    ["work_wages", "debt_credit"],
    ["work_wages", "street_mobilization"],
    ["debt_credit", "assignats"],
    ["assignats", "bread_flow"],
    ["assignats", "black_market"],
    ["property_biens", "assignats"],
    ["property_biens", "suspicion_terror"],
    ["church_oath", "vendee_province"],
    ["church_oath", "property_biens"],
    ["representation_law", "church_oath"],
    ["representation_law", "assignats"],
    ["representation_law", "faction_club"],
    ["press_rumor", "street_mobilization"],
    ["press_rumor", "suspicion_terror"],
    ["street_mobilization", "representation_law"],
    ["street_mobilization", "suspicion_terror"],
    ["army_war", "requisitions"],
    ["army_war", "suspicion_terror"],
    ["army_war", "vendee_province"],
    ["requisitions", "bread_flow"],
    ["requisitions", "vendee_province"],
    ["vendee_province", "suspicion_terror"],
    ["patronage_secrets", "suspicion_terror"],
    ["faction_club", "suspicion_terror"],
    ["suspicion_terror", "property_biens"],
    ["black_market", "suspicion_terror"],
    ["medicine_aid", "street_mobilization"]
  ],
  moves: [
    { id: "buy_bread", title: "Купить или получить хлеб", tags: ["bread"], needs: "деньги, помощь или долг", gives: "хлеб", cost: "монеты/ассигнаты/зависимость", opens: "снятие голода или новая очередь", condition: "Всегда, если хлеб физически есть." },
    { id: "buy_grain", title: "Купить зерно для выпечки", tags: ["bread", "money"], needs: "монеты, доступ к провинции или обозу, перевозчик", gives: "зерно у булочника на следующий ход", cost: "пошлина, задержка, риск срыва подвоза", opens: "выпечка хлеба, налоговый конфликт, нападение на обоз", condition: "Когда денег достаточно, но готового хлеба на рынке мало." },
    { id: "bread_march", title: "Устроить хлебный марш", tags: ["bread", "street"], needs: "5+ голодных или цена хлеба 4+", gives: "давление на Контору/Ассамблею", cost: "риск ареста и насилия", opens: "уступка, Максимум, бунт", condition: "Цена хлеба 4+ или голодных 5+." },
    { id: "hide_grain", title: "Спрятать зерно или товар", tags: ["bread", "black"], needs: "запас или доступ к поставке", gives: "скрытый запас", cost: "подозрение", opens: "черный рынок, обыск, донос", condition: "Есть дефицит, Максимум или риск реквизиции." },
    { id: "refuse_assignat", title: "Отказаться от ассигната", tags: ["money", "black"], needs: "товар или власть отказать", gives: "сохранение стоимости", cost: "сделка срывается, подозрение", opens: "курс вниз, черный рынок вверх", condition: "Курс ассигната ниже 50 или 3+ отказа." },
    { id: "take_work", title: "Взять работу или заказ", tags: ["work"], needs: "работодатель, карточка работы", gives: "доход/хлеб", cost: "время, зависимость", opens: "долг при невыплате", condition: "Всегда, если есть заказ, материал или наниматель." },
    { id: "write_decree", title: "Собрать декрет", tags: ["politics"], needs: "голоса, подписи, печать", gives: "новое правило", cost: "побочный трек", opens: "новый кризис через цену решения", condition: "Есть Ассамблея/клуб и публичная проблема." },
    { id: "take_oath", title: "Присягнуть или отказаться", tags: ["religion"], needs: "духовный статус", gives: "жалованье или доверие прихода", cost: "раскол, подозрение", opens: "Вандея, подпольная церковь", condition: "После церковной реформы или давления государства." },
    { id: "requisition", title: "Реквизировать ресурс", tags: ["war"], needs: "приказ, комиссар/армия", gives: "государственный ресурс", cost: "деревенская злость", opens: "Вандея, снабжение фронта", condition: "Война активна или казна не справляется." },
    { id: "volunteer_army", title: "Пойти в армию", tags: ["war", "work"], needs: "армейский стол", gives: "военный статус, аванс, статус", cost: "фронтовой риск", opens: "карьера, подавление, переворот", condition: "Особенно выгодно бедным при безработице/голоде." },
    { id: "denounce", title: "Донести", tags: ["repression", "street"], needs: "улика, слух или свидетель", gives: "SUSPICION цели", cost: "ответный донос, страх", opens: "обыск, арест, конфискация", condition: "При войне, поражении, Терроре или языке врага." },
    { id: "buy_bien", title: "Купить биен", tags: ["property", "money"], needs: "капитал или ассигнаты", gives: "собственность", cost: "ненависть проигравших, риск отката", opens: "новая элита", condition: "После конфискации церковного/эмигрантского имущества." },
    { id: "start_vendee", title: "Начать провинциальное сопротивление", tags: ["province", "religion", "war"], needs: "4+ участников и повод", gives: "мятеж", cost: "подавление, гибель, конфискации", opens: "внутренний фронт", condition: "Присяга + реквизиции/набор + недоверие к Парижу." },
    { id: "aid_heal", title: "Помочь голодному или больному", tags: ["aid", "bread"], needs: "хлеб, фонд или лекарство", gives: "снятие метки", cost: "фонд истощается", opens: "доверие или обида обойденных", condition: "Есть голод/болезнь и кто-то с фондом/лекарством." }
  ],
  concreteTurn: {
    title: "Акт II, такт 7: хлеб, бумага, война",
    context: "Демо-ход для плейтеста. Максимум держит легальную цену хлеба на 3, но черный рынок уже дороже; казна платит ассигнатами; война открыла реквизиции.",
    rules: [
      "1 GRAIN у булочника = 2 BREAD на рынке",
      "легальная цена BREAD = 3 COIN/ASSIGNAT",
      "черная цена BREAD = 6 COIN",
      "курс ASSIGNAT = 50% от COIN",
      "обычный персонаж сдает 1 BREAD в конце такта; бедные с семьей - 2 BREAD"
    ],
    poolsStart: [
      { id: "marketBread", label: "Хлеб на рынке", value: 28, unit: "BREAD" },
      { id: "churchBread", label: "Церковный фонд", value: 5, unit: "BREAD" },
      { id: "blackBread", label: "Черный рынок", value: 6, unit: "BREAD" },
      { id: "bakerGrain", label: "Зерно у булочника", value: 4, unit: "GRAIN" },
      { id: "treasuryCoin", label: "Казна монетой", value: 8, unit: "COIN" },
      { id: "treasuryAssignat", label: "Казна бумагой", value: 40, unit: "ASSIGNAT" },
      { id: "suspicion", label: "Новые подозрения", value: 0, unit: "меток" },
      { id: "assignatRefusals", label: "Отказы от бумаги", value: 0, unit: "отказов" },
      { id: "ruralAnger", label: "Деревенская злость", value: 0, unit: "сдвигов" },
      { id: "streetPressure", label: "Уличное давление", value: 0, unit: "сдвигов" }
    ],
    transactions: [
      {
        id: "T01",
        phase: "Доход/подвоз",
        relation: "bread_flow",
        actor: "Булочник",
        counterparty: "Виноторговец + обоз G-07",
        receives: "2 GRAIN",
        pays: "2 COIN перевозчику + 1 COIN пошлина",
        result: "зерно дошло до печи; налоговая стена получила видимую цену",
        poolDelta: { bakerGrain: 2, treasuryCoin: 1 }
      },
      {
        id: "T02",
        phase: "Производство",
        relation: "bread_flow",
        actor: "Булочник",
        counterparty: "Печь/рынок",
        receives: "4 BREAD на рынок",
        pays: "2 GRAIN",
        result: "появился хлеб, который можно купить или распределить",
        poolDelta: { bakerGrain: -2, marketBread: 4 }
      },
      {
        id: "T03",
        phase: "Работа",
        relation: "work_wages",
        actor: "Подёнщик",
        counterparty: "Булочник",
        receives: "1 BREAD + 1 COIN",
        pays: "работа: разгрузить зерно",
        result: "подёнщик получает шанс закрыть семейную потребность; булочник закрыл производство",
        poolDelta: { marketBread: -1 }
      },
      {
        id: "T04",
        phase: "Покупка хлеба",
        relation: "bread_flow",
        actor: "Прачка",
        counterparty: "Булочник",
        receives: "1 BREAD",
        pays: "3 ASSIGNAT по Максимуму",
        result: "покупка прошла только при свидетеле секции; булочник получил бумагу с реальной ценностью 1.5 COIN",
        poolDelta: { marketBread: -1 }
      },
      {
        id: "T05",
        phase: "Покупка хлеба",
        relation: "bread_flow",
        actor: "Торговка",
        counterparty: "Булочник",
        receives: "1 BREAD",
        pays: "3 COIN",
        result: "торговка сыта, но получает повод давить за дешевый хлеб для рынка",
        poolDelta: { marketBread: -1 }
      },
      {
        id: "T06",
        phase: "Покровительство",
        relation: "patronage_secrets",
        actor: "Служанка",
        counterparty: "Ламбаль",
        receives: "1 BREAD",
        pays: "работа в доме + молчание о разговоре",
        result: "личная зависимость превращается в доступ к сведениям",
        poolDelta: {}
      },
      {
        id: "T07",
        phase: "Помощь",
        relation: "medicine_aid",
        actor: "Подёнщик",
        counterparty: "Кюре",
        receives: "1 BREAD из церковного фонда",
        pays: "подпись под петицией о хлебе",
        result: "церковь снижает голод, но втягивается в уличную политику",
        poolDelta: { churchBread: -1, streetPressure: 1 }
      },
      {
        id: "T08",
        phase: "Помощь",
        relation: "medicine_aid",
        actor: "Солдат-инвалид",
        counterparty: "Кюре",
        receives: "1 BREAD",
        pays: "обещание поддержать приход публично",
        result: "ветеран становится обязан церкви, а не только государству",
        poolDelta: { churchBread: -1 }
      },
      {
        id: "T09",
        phase: "Черный рынок",
        relation: "black_market",
        actor: "Лавочник",
        counterparty: "Спекулянт",
        receives: "1 BREAD",
        pays: "6 COIN",
        result: "лавочник спасает свой дом, но получает SUSPICION за обход Максимума",
        poolDelta: { blackBread: -1, suspicion: 1 }
      },
      {
        id: "T10",
        phase: "Ассигнаты",
        relation: "assignats",
        actor: "Виноторговец",
        counterparty: "Ролан",
        receives: "ничего: сделка сорвана",
        pays: "отказ принять 5 ASSIGNAT за поставку",
        result: "фиксируется отказ от бумаги; курс ассигната под давлением",
        poolDelta: { assignatRefusals: 1 }
      },
      {
        id: "T11",
        phase: "Жалованье",
        relation: "army_war",
        actor: "Журдан",
        counterparty: "Казна",
        receives: "3 ASSIGNAT жалованья",
        pays: "статус SOLDIER и готовность к приказу",
        result: "солдат формально оплачен, реально получил стоимость 1.5 COIN",
        poolDelta: { treasuryAssignat: -3 }
      },
      {
        id: "T12",
        phase: "Кредит",
        relation: "debt_credit",
        actor: "Людовик XVI / казна",
        counterparty: "Неккер",
        receives: "5 COIN займа",
        pays: "DUE 6 COIN к следующему такту",
        result: "казна покупает один ход времени ценой зависимости от кредитора",
        poolDelta: { treasuryCoin: 5 }
      },
      {
        id: "T13",
        phase: "Порядок",
        relation: "street_mobilization",
        actor: "Лафайет",
        counterparty: "Казна",
        receives: "3 COIN на гвардейский караул рынка",
        pays: "ORDER: держать очередь без погрома",
        result: "улица временно сдержана, но гвардия становится политическим актором",
        poolDelta: { treasuryCoin: -3 }
      },
      {
        id: "T14",
        phase: "Реквизиция",
        relation: "requisitions",
        actor: "Каррье",
        counterparty: "Провинция/NPC",
        receives: "2 GRAIN для армии",
        pays: "4 ASSIGNAT компенсации",
        result: "армия получает снабжение; деревня получает злость за бумажную компенсацию",
        poolDelta: { treasuryAssignat: -4, ruralAnger: 1 }
      },
      {
        id: "T15",
        phase: "Печать",
        relation: "press_rumor",
        actor: "Марат",
        counterparty: "Типограф",
        receives: "20 LEAFLET о хлебе и спекулянтах",
        pays: "2 COIN + 1 PAPER",
        result: "частная покупка печати становится массовым обвинением",
        poolDelta: { streetPressure: 1 }
      },
      {
        id: "T16",
        phase: "Петиция",
        relation: "faction_club",
        actor: "Дантон / Робеспьер",
        counterparty: "Торговка + Подёнщик + Прачка",
        receives: "6 подписей под требованием контроля хлеба",
        pays: "обещание вынести вопрос в секцию",
        result: "бытовая нехватка превращается в политический документ",
        poolDelta: { streetPressure: 1 }
      },
      {
        id: "T17",
        phase: "Донос",
        relation: "suspicion_terror",
        actor: "Фуше",
        counterparty: "Служанка",
        receives: "донос: у лавочника спрятан хлеб",
        pays: "PROTECTION 1 для служанки",
        result: "информация становится защитой для одного и угрозой для другого",
        poolDelta: { suspicion: 1 }
      },
      {
        id: "T18",
        phase: "Обыск",
        relation: "suspicion_terror",
        actor: "Фукье-Тенвиль",
        counterparty: "Лавочник",
        receives: "1 HIDDEN BREAD найден и возвращен на рынок",
        pays: "ORDER обыска + SUSPICION лавочнику",
        result: "рынок получает хлеб, но страх и логика доноса усиливаются",
        poolDelta: { marketBread: 1, suspicion: 1 }
      },
      {
        id: "T19",
        phase: "Присяга",
        relation: "church_oath",
        actor: "Кюре",
        counterparty: "Приход",
        receives: "2 COIN пожертвований",
        pays: "отказ принести присягу сейчас",
        result: "приходское доверие растет, юридический риск REFRACTORY появляется",
        poolDelta: {}
      },
      {
        id: "T20",
        phase: "Лечение",
        relation: "medicine_aid",
        actor: "Хирург",
        counterparty: "Солдат-инвалид",
        receives: "1 COIN из церковного фонда",
        pays: "1 MEDICINE и лечение",
        result: "с инвалида снята SICK, но он обязан кюре/хирургу",
        poolDelta: {}
      },
      {
        id: "T21",
        phase: "Фоновые продажи",
        relation: "bread_flow",
        actor: "Рынок",
        counterparty: "прочие игроки",
        receives: "72 COIN/ASSIGNAT номиналом",
        pays: "24 BREAD обычным покупателям",
        result: "после активных сцен видно, сколько хлеба осталось для опоздавших",
        poolDelta: { marketBread: -24 }
      }
    ],
    closingChecks: [
      { actor: "Подёнщик", has: "старт 1 BREAD + работа 1 + помощь 1 = 3", needs: "2 BREAD", result: "сдает 2, остается 1; голода нет, но есть долг благодарности к кюре" },
      { actor: "Прачка", has: "старт 1 BREAD + покупка 1 = 2", needs: "2 BREAD", result: "закрывает семью без запаса" },
      { actor: "Служанка", has: "старт 1 BREAD + покровительство 1 = 2", needs: "1 BREAD", result: "сыта, но связана с Ламбаль и Фуше" },
      { actor: "Лавочник", has: "старт 1 BREAD + черный рынок 1", needs: "1 BREAD", result: "сыт, но получает 3 подозрения за черный хлеб, донос и обыск" },
      { actor: "Солдат-инвалид", has: "старт 1 BREAD + помощь 1", needs: "1 BREAD", result: "сыт, болезнь снята; обязан приходу" }
    ]
  }
};

window.REVOLUTION_CHARACTER_RELATIONS.concreteTurn = {
  title: "Акт I, ход 1: хлеб, налоги, созыв штатов",
  context: "Первый обучающий ход. Ассигнатов еще нет, войны нет, старые платежи действуют. Задача хода: бедные ищут второй хлеб, рынок показывает цену подвоза, казна ищет деньги, депутаты превращают бытовую боль в политическое требование.",
  rules: [
    "деньги не создают хлеб: сначала нужно купить и довезти зерно",
    "1 мешок зерна у булочника = 2 буханки хлеба на рынке",
    "цена хлеба = 2 монеты",
    "ассигнатов еще нет",
    "война и реквизиции еще закрыты",
    "обычный персонаж сдает 1 буханку хлеба в конце хода; Подёнщик и Прачка с семьей - 2 буханки"
  ],
  distribution: [
    { who: "Все персонажи", gets: "личная карточка, стартовые монеты по роли, 1 буханка хлеба", note: "это базовая еда; бедные с семьей все равно должны найти второй хлеб" },
    { who: "Людовик XVI", gets: "12 монет, 2 буханки хлеба, двор как собственность, государственный долг", note: "личный ресурс связан с казной; долг сразу политическая проблема" },
    { who: "Мария-Антуанетта, Артуа, Прованский, Полиньяк, Ламбаль, Ферзен", gets: "8-12 монет, 1-2 буханки хлеба, придворная собственность/права", note: "могут нанимать, давать защиту, эмигрировать позже" },
    { who: "Неккер", gets: "18 монет, расписка госдолга, финансовая работа", note: "может дать казне заем и купить время" },
    { who: "Сийес, Талейран, Мори", gets: "6-10 монет, 1 буханка хлеба, право на церковный доход", note: "церковный ресурс пока работает, но станет целью реформ" },
    { who: "Кюре", gets: "2 монеты, 1 буханка хлеба, доступ к церковному фонду: 5 буханок", note: "может спасать бедных хлебом и брать подписи/доверие" },
    { who: "Лафайет, Буйе, Дюмурье, Наполеон, Журдан, Пишегрю, Моро", gets: "3-9 монет, 1 буханка хлеба, армейский статус/работа", note: "на первом ходу армия скорее порядок и престиж, не фронт" },
    { who: "Депутаты и адвокаты", gets: "3-6 монет, 1 буханка хлеба, работа речи/мандата/клуба", note: "их ход - собрать голоса, петиции, процедуру" },
    { who: "Печать: Марат, Эбер, Демулен, Бриссо, Типограф", gets: "2-5 монет, 1 буханка хлеба, печатная работа; Типограф получает 1 лист бумаги", note: "могут превращать хлеб и налоги в слух/памфлет" },
    { who: "Булочник", gets: "5 монет, 3 буханки хлеба, 1 мешок зерна, печь как собственность", note: "центральный узел: без зерна рынка не хватит" },
    { who: "Лавочник, Откупщик, Торговка, Хозяин кафе, Столяр", gets: "4-7 монет, 1 буханка хлеба, лавка/место/контора/мастерская", note: "дают работу, кредит, слухи, сборы и конфликт цены" },
    { who: "Подёнщик и Прачка", gets: "1-2 монеты, 1 буханка хлеба, потребность семьи: 2 буханки", note: "обязаны найти работу, долг, помощь или купить хлеб" },
    { who: "Служанка, Актриса, Солдат-инвалид", gets: "2-3 монеты, 1 буханка хлеба, работа/покровитель/ветеранский статус", note: "могут идти к нанимателям, церкви, гвардии или в слухи" }
  ],
  poolsStart: [
    { id: "marketBread", label: "Хлеб на рынке", value: 40, unit: "буханок" },
    { id: "churchBread", label: "Церковный фонд", value: 5, unit: "буханок" },
    { id: "roadGrain", label: "Зерно в дороге", value: 10, unit: "мешков" },
    { id: "bakerGrain", label: "Зерно у булочника", value: 5, unit: "мешков" },
    { id: "treasuryCoin", label: "Казна монетой", value: 10, unit: "монет" },
    { id: "treasuryAssignat", label: "Казна бумагой", value: 0, unit: "ассигнатов" },
    { id: "taxDue", label: "Налоговые требования", value: 12, unit: "квитанций" },
    { id: "newDebt", label: "Новые долги", value: 0, unit: "расписок" },
    { id: "hunger", label: "Новый голод", value: 0, unit: "меток" },
    { id: "suspicion", label: "Новые подозрения", value: 0, unit: "меток" },
    { id: "ruralAnger", label: "Деревенская злость", value: 0, unit: "сдвигов" },
    { id: "streetPressure", label: "Уличное давление", value: 0, unit: "сдвигов" }
  ],
  transactions: [
    {
      id: "T01",
      phase: "Доход/подвоз",
      relation: "bread_flow",
      actor: "Булочник",
      counterparty: "застава Бертье + обоз G-01",
      receives: "2 мешка зерна",
      pays: "2 монеты перевозчику + 1 монета пошлина",
      result: "зерно дошло до печи; налоговая стена стала видимой причиной цены",
      poolDelta: { roadGrain: -2, bakerGrain: 2, treasuryCoin: 1 }
    },
    {
      id: "T02",
      phase: "Производство",
      relation: "bread_flow",
      actor: "Булочник",
      counterparty: "Печь/рынок",
      receives: "4 буханки хлеба на рынок",
      pays: "2 мешка зерна",
      result: "появился хлеб, который можно купить или распределить",
      poolDelta: { bakerGrain: -2, marketBread: 4 }
    },
    {
      id: "T03",
      phase: "Работа",
      relation: "work_wages",
      actor: "Подёнщик",
      counterparty: "Булочник",
      receives: "1 буханка хлеба + 1 монета",
      pays: "работа: разгрузить зерно",
      result: "подёнщик получает шанс закрыть семейную потребность; булочник закрыл производство",
      poolDelta: { marketBread: -1 }
    },
    {
      id: "T04",
      phase: "Покупка хлеба",
      relation: "bread_flow",
      actor: "Прачка",
      counterparty: "Булочник",
      receives: "1 буханка хлеба",
      pays: "2 монеты",
      result: "прачка закрывает семейную потребность, но остается без запаса",
      poolDelta: { marketBread: -1 }
    },
    {
      id: "T05",
      phase: "Покупка хлеба",
      relation: "bread_flow",
      actor: "Торговка",
      counterparty: "Булочник",
      receives: "1 буханка хлеба",
      pays: "2 монеты",
      result: "торговка сыта, но видит очередь и получает повод кричать о цене",
      poolDelta: { marketBread: -1 }
    },
    {
      id: "T06",
      phase: "Покровительство",
      relation: "patronage_secrets",
      actor: "Служанка",
      counterparty: "Ламбаль",
      receives: "1 буханка хлеба",
      pays: "работа в доме + молчание о разговоре",
      result: "личная зависимость превращается в доступ к сведениям",
      poolDelta: {}
    },
    {
      id: "T07",
      phase: "Помощь",
      relation: "medicine_aid",
      actor: "Солдат-инвалид",
      counterparty: "Кюре",
      receives: "1 буханка хлеба из церковного фонда",
      pays: "обещание поддержать приход публично",
      result: "церковь снижает голод и получает публичного защитника",
      poolDelta: { churchBread: -1 }
    },
    {
      id: "T08",
      phase: "Десятина",
      relation: "church_oath",
      actor: "Кюре",
      counterparty: "приход/NPC",
      receives: "1 буханка хлеба в церковный фонд",
      pays: "старое право десятины",
      result: "фонд растет, но деревня получает первый раздражитель",
      poolDelta: { churchBread: 1, ruralAnger: 1 }
    },
    {
      id: "T09",
      phase: "Налог",
      relation: "tax_wall",
      actor: "Откупщик Бертье",
      counterparty: "торговцы у заставы",
      receives: "2 монеты в казну",
      pays: "квитанция об уплате octroi",
      result: "налог становится публичным конфликтом; Бертье защищает сбор, а торговцы ищут обход стены",
      poolDelta: { treasuryCoin: 2, taxDue: -1 }
    },
    {
      id: "T10",
      phase: "Сеньориальный платеж",
      relation: "property_biens",
      actor: "Казалес",
      counterparty: "провинция/NPC",
      receives: "2 монеты сеньориального платежа",
      pays: "старое право и защита архива",
      result: "дворянин получает доход, деревня копит злость к правам",
      poolDelta: { ruralAnger: 1 }
    },
    {
      id: "T11",
      phase: "Кредит",
      relation: "debt_credit",
      actor: "Людовик XVI / казна",
      counterparty: "Неккер",
      receives: "5 монет займа",
      pays: "расписка: вернуть 6 монет к следующему ходу",
      result: "казна покупает один ход времени ценой зависимости от кредитора",
      poolDelta: { treasuryCoin: 5, newDebt: 1 }
    },
    {
      id: "T12",
      phase: "Порядок",
      relation: "street_mobilization",
      actor: "Лафайет",
      counterparty: "Казна",
      receives: "2 монеты на гвардейский караул рынка",
      pays: "поручение: держать очередь без погрома",
      result: "улица временно сдержана, но гвардия становится политическим актором",
      poolDelta: { treasuryCoin: -2 }
    },
    {
      id: "T13",
      phase: "Памфлет",
      relation: "press_rumor",
      actor: "Сийес",
      counterparty: "Типограф",
      receives: "20 LEAFLET о третьем сословии",
      pays: "1 монета + 1 лист бумаги",
      result: "идея представительства получает физический тираж",
      poolDelta: {}
    },
    {
      id: "T14",
      phase: "Слух",
      relation: "press_rumor",
      actor: "Марат",
      counterparty: "Хозяин кафе",
      receives: "слух: хлеб дорог из-за пошлин и спекулянтов",
      pays: "обещание напечатать обвинение",
      result: "очередь получает виновника, а не просто цену",
      poolDelta: { streetPressure: 1 }
    },
    {
      id: "T15",
      phase: "Петиция",
      relation: "representation_law",
      actor: "Мирабо / Байи",
      counterparty: "Подёнщик + Прачка + Торговка",
      receives: "5 подписей о хлебе и налогах",
      pays: "обещание поднять вопрос процедуры и налогов",
      result: "бытовая нехватка входит в политическую повестку",
      poolDelta: { streetPressure: 1 }
    },
    {
      id: "T16",
      phase: "Долг",
      relation: "debt_credit",
      actor: "Дантон",
      counterparty: "Подёнщик",
      receives: "расписка на 2 монеты после следующей работы",
      pays: "1 монета взаймы",
      result: "подёнщик получает маневр, Дантон получает зависимого союзника",
      poolDelta: { newDebt: 1 }
    },
    {
      id: "T17",
      phase: "Помощь",
      relation: "bread_flow",
      actor: "Подёнщик",
      counterparty: "Кюре",
      receives: "1 буханка хлеба из церковного фонда",
      pays: "подпись под петицией о хлебе",
      result: "второй хлеб получен не через рынок, а через церковь и политику",
      poolDelta: { churchBread: -1, streetPressure: 1 }
    },
    {
      id: "T18",
      phase: "Кредитная продажа",
      relation: "debt_credit",
      actor: "Лавочник",
      counterparty: "Служанка",
      receives: "расписка на 1 монету",
      pays: "мелкий товар в долг",
      result: "лавочник получает власть над бедной ролью без прямого насилия",
      poolDelta: { newDebt: 1 }
    },
    {
      id: "T19",
      phase: "Салон",
      relation: "patronage_secrets",
      actor: "Манон Ролан",
      counterparty: "Лафайет",
      receives: "публичный голос и доступ к залу",
      pays: "черновик речи о конституции, свободе торговли и налоговой стене",
      result: "Лафайет восхищается её умом; салон получает трибуну, а Бертье - политическую угрозу",
      poolDelta: {}
    },
    {
      id: "T20",
      phase: "Фоновые покупки",
      relation: "bread_flow",
      actor: "Рынок",
      counterparty: "прочие игроки",
      receives: "60 монет номиналом",
      pays: "30 буханок хлеба обычным покупателям",
      result: "после активных сцен видно, сколько хлеба осталось для опоздавших",
      poolDelta: { marketBread: -30 }
    },
    {
      id: "T21",
      phase: "Закрытие",
      relation: "bread_flow",
      actor: "3 опоздавших бедных NPC/массовка",
      counterparty: "мастер закрытия",
      receives: "метка голода",
      pays: "не смогли купить хлеб до конца хода",
      result: "порог бунта еще не открыт, но у улицы есть первые красные метки",
      poolDelta: { hunger: 3, streetPressure: 1 }
    }
  ],
  closingChecks: [
    { actor: "Подёнщик", has: "старт 1 хлеб + работа 1 + помощь 1 = 3 буханки", needs: "2 буханки", result: "сдает 2, остается 1; голода нет, но есть долг/связь с кюре и Дантоном" },
    { actor: "Прачка", has: "старт 1 хлеб + покупка 1 = 2 буханки", needs: "2 буханки", result: "закрывает семью без запаса" },
    { actor: "Служанка", has: "старт 1 хлеб + хлеб от Ламбаль = 2 буханки", needs: "1 буханка", result: "сыта, но связана с домом Ламбаль и долгом лавочнику" },
    { actor: "Солдат-инвалид", has: "старт 1 хлеб + помощь кюре = 2 буханки", needs: "1 буханка", result: "сыт; становится публичным защитником прихода" },
    { actor: "Казна", has: "10 старт + 1 пошлина + 2 налог + 5 заем - 2 гвардия = 16", needs: "платежи и доверие", result: "дыра не закрыта, но первый ход куплен" },
    { actor: "Рынок", has: "40 старт + 4 выпечено - 33 продано/выдано = 11", needs: "подвоз следующего хода", result: "катастрофы нет, но без нового зерна ход 2 станет дороже" }
  ]
};

window.REVOLUTION_CHARACTER_RELATIONS.resourceModel = {
  title: "Откуда берутся ресурсы и кому они принадлежат",
  context: "Главное разделение: ресурс может быть личным, фондовым или государственным. Персонаж может иметь доступ к фонду, но это еще не значит, что он может забрать его себе без цены.",
  principles: [
    "Деньги покупают не сытость, а конкретный следующий шаг: зерно, подвоз, работу булочника или уже готовый хлеб.",
    "Личный ресурс тратится персонажем свободно; государственный ресурс тратится только через должность, приказ, квитанцию или декрет.",
    "Фондовый ресурс принадлежит институту: церкви, лавке, типографии, клубу, гвардии. У персонажа есть доступ, но не полная личная собственность.",
    "Любой перевод между кошельками создает след: долг, налоговую квитанцию, благодарность, подозрение, слух или политическое требование."
  ],
  sources: [
    { source: "Стартовая раздача", who: "все роли", gives: "монеты, хлеб, статус, долги, доступ к фондам", limit: "один раз в начале акта или хода" },
    { source: "Работа и заказ", who: "бедные, ремесленники, военные, печать", gives: "монеты, хлеб, расписку, покровительство", limit: "нужен наниматель и понятная работа" },
    { source: "Продажа товара", who: "булочник, лавочник, торговка, типограф", gives: "монеты или расписку", limit: "нужен физический товар: хлеб, зерно, бумага, услуга" },
    { source: "Производство", who: "булочник, мастерские, типография", gives: "новый товар", limit: "нужны сырье, время и рабочие руки" },
    { source: "Подвоз", who: "торговцы, богатые заказчики, государство", gives: "зерно, товар, армейское снабжение", limit: "нужны монеты, перевозчик, дорога; возможна задержка" },
    { source: "Собственность и права", who: "дворяне, церковь, буржуа, владельцы лавок", gives: "ренту, платежи, доступ, защиту", limit: "вызывает конфликт прав и налогов" },
    { source: "Долг и кредит", who: "Неккер, Дантон, лавочники, богатые", gives: "монеты сейчас", limit: "создает расписку и зависимость" },
    { source: "Налоги и пошлины", who: "казна, откупщики, сборщики, муниципалитет", gives: "государственные монеты", limit: "создает злость и повод для политики" },
    { source: "Фонд помощи", who: "кюре, благотворители, приход", gives: "хлеб, лечение, защиту", limit: "фонд истощается, обойденные злятся" },
    { source: "Политическое решение", who: "Ассамблея, король, муниципалитет, комитеты", gives: "новый доступ к казне, налогам, имуществу, реквизициям", limit: "нужны голоса/приказ; появляется публичная цена" }
  ],
  wallets: [
    {
      kind: "Личное",
      owner: "конкретный персонаж",
      examples: "монеты на руках, хлеб на руках, личное зерно, лавка, инструмент, расписка, сведения, покровительство",
      canSpend: "сам персонаж",
      cannotDo: "не может объявить это казной или городским запасом без сделки",
      moveToState: "налог, заем казне, пожертвование, конфискация",
      moveFromState: "жалованье, подряд, пенсия, награда"
    },
    {
      kind: "Фондовое",
      owner: "институт или место",
      examples: "церковный фонд, склад лавки, бумага типографии, клубная касса, гвардейский фонд",
      canSpend: "персонаж с доступом или должностью",
      cannotDo: "не может забрать себе без слуха, проверки или обвинения",
      moveToState: "учет, реквизиция, налог, декрет",
      moveFromState: "субсидия, заказ, охрана, жалованье"
    },
    {
      kind: "Государственное",
      owner: "казна, муниципалитет, армия, государственный склад",
      examples: "казна монетой, налоговые требования, армейское снабжение, реквизированное зерно, государственный долг",
      canSpend: "должностное лицо через приказ, декрет, квитанцию",
      cannotDo: "король или министр не тратит это как личный кошелек без политической цены",
      moveToState: "налоги, пошлины, заем, реквизиция, конфискация",
      moveFromState: "жалованье, закупка зерна, караул, помощь, подряд"
    },
    {
      kind: "Общественный пул",
      owner: "мастера как состояние города",
      examples: "хлеб на рынке, зерно в дороге, голод, уличное давление, деревенская злость, подозрение",
      canSpend: "никто напрямую; игроки могут только сдвигать через действия",
      cannotDo: "нельзя забрать весь пул одной фразой; нужна сцена покупки, подвоза, раздачи или насилия",
      moveToState: "учет, контроль цен, реквизиция, охрана рынка",
      moveFromState: "закупка, раздача, открытие складов, подавление очереди"
    }
  ],
  transfers: [
    { from: "Личное", to: "Личное", action: "сделка, подарок, долг, найм", example: "Дантон дает подёнщику 1 монету, получает расписку на 2 монеты" },
    { from: "Личное", to: "Фондовое", action: "пожертвование, вклад товара, заказ печати", example: "Сийес платит типографу монету и бумагу за листовки" },
    { from: "Фондовое", to: "Личное", action: "помощь, продажа, выдача пайка", example: "Кюре дает солдату-инвалиду 1 буханку из церковного фонда" },
    { from: "Личное", to: "Государственное", action: "налог, пошлина, заем казне", example: "Неккер дает казне 5 монет, казна выдает расписку на 6" },
    { from: "Государственное", to: "Личное", action: "жалованье, пенсия, подряд, оплата караула", example: "Лафайет получает 2 монеты из казны на караул рынка" },
    { from: "Общественный пул", to: "Личное", action: "покупка на рынке, очередь, распределение", example: "Прачка платит 2 монеты и получает 1 буханку с рынка" },
    { from: "Личное", to: "Общественный пул", action: "продажа, выпечка, открытие склада", example: "Булочник тратит 2 мешка зерна и добавляет 4 буханки на рынок" },
    { from: "Государственное", to: "Общественный пул", action: "закупка зерна, охрана, раздача", example: "Казна оплачивает подвоз; зерно появится в дороге, а не сразу в руках игроков" }
  ]
};

window.REVOLUTION_CHARACTER_RELATIONS.incomeModel = {
  title: "Доходы персонажей за ход",
  context: "Доход - это не все богатство персонажа, а то, что он может регулярно получить за один ход, если источник работает. Собственность и должность дают доступ, но не всегда дают личные монеты.",
  rules: [
    "Стартовый запас выдается один раз; доход проверяется каждый ход.",
    "Фондовый и государственный доход нельзя забрать себе без следа: нужна квитанция, приказ, жалованье, заем или злоупотребление.",
    "Рыночный доход требует товара; хлебный доход требует зерна и выпечки.",
    "Бедные чаще получают не деньги, а связку: 1 монета, хлеб, долг или покровительство."
  ],
  rows: [
    { characterId: "sieyes", start: "6 монет, 1 хлеб", income: "2 монеты/ход", source: "церковная должность, тексты, политический заказ", kind: "личное + церковный доступ", condition: "до церковной реформы; после реформы источник спорный" },
    { characterId: "talleyrand", start: "10 монет, 1 хлеб", income: "3 монеты/ход", source: "епископские доходы, собственность, связи", kind: "личное + фондовое", condition: "может конвертировать связи в деньги, но церковное имущество под ударом" },
    { characterId: "maury", start: "6 монет, 1 хлеб", income: "2 монеты/ход", source: "церковная рента, покровители, речь", kind: "личное", condition: "падает при атаке на духовенство" },
    { characterId: "cure", start: "2 монеты, 1 хлеб, церковный фонд", income: "1 монета/ход + доступ к фонду помощи", source: "приход, десятина, пожертвования", kind: "личное + фондовое", condition: "фонд раздается бедным, но не является личным кошельком" },
    { characterId: "lafayette", start: "9 монет, 1 хлеб", income: "2 монеты/ход", source: "собственность, военная должность, политический вес", kind: "личное + государственный доступ", condition: "деньги на гвардию идут через приказ, не в личный карман" },
    { characterId: "louis_xvi", start: "12 монет, 2 хлеба", income: "2 монеты/ход лично; казна отдельно", source: "дворовое содержание, королевская собственность", kind: "личное + государственный доступ", condition: "казну тратит через приказ/министра; личные деньги не равны казне" },
    { characterId: "marie_antoinette", start: "12 монет, 2 хлеба", income: "3 монеты/ход", source: "дворовое содержание, подарки, покровительство", kind: "личное", condition: "крупная трата повышает слух о дорогом дворе" },
    { characterId: "artois", start: "10 монет, 2 хлеба", income: "3 монеты/ход", source: "рента, двор, старые права", kind: "личное", condition: "после эмиграции доход переходит в риск конфискации" },
    { characterId: "provence", start: "10 монет, 2 хлеба", income: "3 монеты/ход", source: "рента, двор, политический торг", kind: "личное", condition: "может сохранять доход через компромисс" },
    { characterId: "polignac", start: "8 монет, 1 хлеб", income: "3 монеты/ход", source: "пенсии двора, подарки, покровительство", kind: "личное", condition: "особенно видимый доход; дает повод для злости" },
    { characterId: "lamballe", start: "8 монет, 1 хлеб", income: "2 монеты/ход", source: "двор, дом, покровительство", kind: "личное", condition: "может платить слугам хлебом/защитой" },
    { characterId: "fersen", start: "8 монет, 1 хлеб", income: "2 монеты/ход", source: "личное состояние, иностранные связи", kind: "личное", condition: "иностранные деньги дают подозрение" },
    { characterId: "mirabeau", start: "5 монет, 1 хлеб", income: "1 монета/ход честно; до 3 через сделки", source: "речь, тексты, долги, тайные выплаты", kind: "личное", condition: "доход выше 1 монеты требует след: долг или подозрение" },
    { characterId: "charlotte_corday", start: "3 монеты, 1 хлеб", income: "1 монета/ход", source: "семейная поддержка, провинциальная сеть", kind: "личное", condition: "нестабильно в Париже" },
    { characterId: "barras", start: "6 монет, 1 хлеб", income: "2 монеты/ход", source: "собственность, должности, политическая сеть", kind: "личное + должностной доступ", condition: "растет при смене режима" },
    { characterId: "cazales", start: "5 монет, 1 хлеб", income: "2 монеты/ход", source: "сеньориальные платежи, старые права", kind: "личное", condition: "после отмены прав доход спорный или исчезает" },
    { characterId: "dumouriez", start: "6 монет, 1 хлеб", income: "2 монеты/ход", source: "офицерское жалованье, военные поручения", kind: "государственное жалованье", condition: "если казна платит и должность признана" },
    { characterId: "napoleon", start: "3 монеты, 1 хлеб", income: "1 монета/ход", source: "офицерское жалованье", kind: "государственное жалованье", condition: "без войны и заказов доход мал" },
    { characterId: "buonarroti", start: "4 монеты, 1 хлеб", income: "1 монета/ход", source: "семейная собственность, тексты, политическая работа", kind: "личное", condition: "подполье снижает открытый доход" },
    { characterId: "breteuil", start: "8 монет, 1 хлеб", income: "2 монеты/ход", source: "дворовая должность, покровители", kind: "личное + должностной доступ", condition: "падает при падении двора" },
    { characterId: "bouille", start: "7 монет, 1 хлеб", income: "2 монеты/ход", source: "офицерское жалованье, собственность", kind: "личное + государственное", condition: "заговор или эмиграция ломают официальный доход" },
    { characterId: "necker", start: "18 монет, 1 хлеб", income: "3 монеты/ход", source: "капитал, проценты, кредит казне", kind: "личное + кредиторский доступ", condition: "может давать займы; казна не становится его кошельком" },
    { characterId: "bailly", start: "5 монет, 1 хлеб", income: "2 монеты/ход", source: "муниципальная должность, академический статус", kind: "личное + муниципальный доступ", condition: "деньги муниципалитета тратятся через решение" },
    { characterId: "barnave", start: "5 монет, 1 хлеб", income: "2 монеты/ход", source: "адвокатская практика, депутатская работа", kind: "личное", condition: "компромиссы могут давать подозрение" },
    { characterId: "marat", start: "3 монеты, 1 хлеб", income: "1 монета/ход", source: "подписка, памфлет, покровитель", kind: "личное + печатный доступ", condition: "нужны бумага, типограф или скандал" },
    { characterId: "robespierre", start: "4 монеты, 1 хлеб", income: "1 монета/ход", source: "адвокатская практика, депутатское содержание", kind: "личное", condition: "богатым не становится, но получает политический капитал" },
    { characterId: "brissot", start: "4 монеты, 1 хлеб", income: "1 монета/ход", source: "газета, сеть корреспондентов", kind: "личное + печатный доступ", condition: "нужны бумага и читатели" },
    { characterId: "roland", start: "6 монет, 1 хлеб", income: "2 монеты/ход", source: "административная должность, имущество", kind: "личное + государственный доступ", condition: "ассигнаты и служба меняют качество дохода" },
    { characterId: "manon_roland", start: "4 монеты, 1 хлеб", income: "0-1 монета/ход", source: "дом, салон, переписка, поддержка Ролана", kind: "домашний/сетевой ресурс", condition: "главный доход - контакты, а не монеты" },
    { characterId: "vergniaud", start: "5 монет, 1 хлеб", income: "2 монеты/ход", source: "адвокатская практика, речь, депутатская работа", kind: "личное", condition: "фракционная цена растет вместе с доходом влияния" },
    { characterId: "danton", start: "6 монет, 1 хлеб", income: "2 монеты/ход", source: "юридическая практика, займы, политические сделки", kind: "личное", condition: "сверхдоход почти всегда оставляет расписку или слух" },
    { characterId: "saint_just", start: "4 монеты, 1 хлеб", income: "1 монета/ход", source: "семейная поддержка, депутатская работа", kind: "личное", condition: "до комитетов доход скромный" },
    { characterId: "hebert", start: "2 монеты, 1 хлеб", income: "1 монета/ход", source: "листки, клуб, уличная поддержка", kind: "личное + печатный доступ", condition: "нужны тема, бумага и типограф" },
    { characterId: "couthon", start: "4 монеты, 1 хлеб", income: "1 монета/ход", source: "юридическая работа, депутатское содержание", kind: "личное", condition: "комитеты дают власть, но не личный кошелек" },
    { characterId: "desmoulins", start: "3 монеты, 1 хлеб", income: "1 монета/ход", source: "памфлеты, редактура, покровители", kind: "личное + печатный доступ", condition: "слово может стать уликой" },
    { characterId: "carnot", start: "5 монет, 1 хлеб", income: "2 монеты/ход", source: "инженерная служба, военная администрация", kind: "государственное жалованье", condition: "ресурсы армии не личный доход" },
    { characterId: "barere", start: "5 монет, 1 хлеб", income: "2 монеты/ход", source: "адвокатская/депутатская работа, комитет", kind: "личное + должностной доступ", condition: "доступ к решениям не равен личной казне" },
    { characterId: "fouquier_tinville", start: "5 монет, 1 хлеб", income: "2 монеты/ход", source: "судебная должность", kind: "государственное жалованье", condition: "работает, когда открыт репрессивный аппарат" },
    { characterId: "carrier", start: "4 монеты, 1 хлеб", income: "2 монеты/ход", source: "миссия, комиссарские выплаты", kind: "государственное жалованье", condition: "реквизиции проходят через приказ, не как личная добыча без риска" },
    { characterId: "fouche", start: "4 монеты, 1 хлеб", income: "2 монеты/ход", source: "должность, списки, сеть информаторов", kind: "государственное + сетевое", condition: "лишние деньги дают подозрение" },
    { characterId: "tallien", start: "4 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "канцелярия, печать, должность", kind: "личное + должностной доступ", condition: "меняется вместе с режимом" },
    { characterId: "babeuf", start: "2 монеты, 1 хлеб", income: "1 монета/ход", source: "писарская работа, тексты, земельные бумаги", kind: "личное", condition: "бедность толкает к радикальным ходам" },
    { characterId: "moreau", start: "4 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "офицерское жалованье", kind: "государственное жалованье", condition: "зависит от армии и лояльности" },
    { characterId: "larevelliere", start: "4 монеты, 1 хлеб", income: "1 монета/ход", source: "собственность, депутатская работа", kind: "личное", condition: "религиозная политика может ломать поддержку" },
    { characterId: "avocat", start: "3 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "клиенты, жалобы, юридические поручения", kind: "личное", condition: "нужны клиенты или публичный спор" },
    { characterId: "chirurgien", start: "4 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "лечение, больница, частная помощь", kind: "личное + фондовый доступ", condition: "лекарство и фонд не всегда личные" },
    { characterId: "poissarde", start: "4 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "рынок, торговля, доставка товара", kind: "личное", condition: "нужен товар; голодная очередь режет доход" },
    { characterId: "vinier", start: "8 монет, 1 хлеб, книга сборов", income: "2-3 монеты/ход", source: "налоговый откуп, октруа, штрафы, контракты с казной", kind: "личное + государственный доступ", condition: "сборы дают деньги, но каждая квитанция повышает ненависть к стене" },
    { characterId: "cafetier", start: "5 монет, 1 хлеб", income: "1-2 монеты/ход", source: "кафе, напитки, разговоры, слухи", kind: "личное + информационный ресурс", condition: "доход растет от посетителей и скандалов" },
    { characterId: "mercier", start: "5 монет, 1 хлеб", income: "1-2 монеты/ход", source: "лавка, мелкий товар, кредит", kind: "личное + склад", condition: "продажа в долг дает расписку, не сразу монеты" },
    { characterId: "boulanger", start: "5 монет, 3 хлеба, 1 мешок зерна", income: "2-4 монеты/ход", source: "выпечка и продажа хлеба", kind: "личное + рыночный узел", condition: "без зерна доход падает до 0; хлеб не создается из монет" },
    { characterId: "menuisier", start: "4 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "заказы, ремонт, мастерская", kind: "личное + мастерская", condition: "нужен заказчик и материал" },
    { characterId: "imprimeur", start: "5 монет, 1 хлеб, бумага", income: "2-4 монеты/ход", source: "печать листовок, газет, документов", kind: "личное + типографский фонд", condition: "нужны бумага, заказ и риск цензуры" },
    { characterId: "pichegru", start: "4 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "офицерское жалованье", kind: "государственное жалованье", condition: "роялистские связи могут перекрыть официальный доход" },
    { characterId: "jourdan", start: "3 монеты, 1 хлеб", income: "1 монета/ход", source: "солдатское/офицерское жалованье, паек", kind: "государственное жалованье", condition: "казна может платить бумагой или задерживать" },
    { characterId: "lavandiere", start: "2 монеты, 1 хлеб", income: "1 монета или 1 хлеб/ход", source: "стирка, услуга, подработка", kind: "личное", condition: "если нет работы, сразу голод/долг" },
    { characterId: "actrice", start: "2-3 монеты, 1 хлеб", income: "1-2 монеты/ход", source: "театр, покровитель, публика", kind: "личное + покровительство", condition: "цензура или скандал режут доход" },
    { characterId: "invalide", start: "2 монеты, 1 хлеб", income: "1 монета или паек/ход", source: "пенсия, помощь церкви, ветеранский статус", kind: "государственное + фондовое", condition: "если пенсия задержана, идет к церкви/улице" },
    { characterId: "journalier", start: "1 монета, 1 хлеб", income: "1 монета + иногда хлеб/ход", source: "разгрузка, переноска, разовая работа", kind: "личное", condition: "нужен наниматель; семье нужно 2 хлеба" },
    { characterId: "servante", start: "2 монеты, 1 хлеб", income: "1 монета или хлеб/ход", source: "служба в доме, сведения, поручения", kind: "личное + покровительство", condition: "доход зависит от хозяина; сведения можно обменять на защиту" }
  ]
};
