window.FRANCE_CHARACTERS = [
  {
    "id": "mirabeau",
    "name_ru": "Оноре Габриэль де Мирабо",
    "name_fr": "Honoré Gabriel Riqueti, comte de Mirabeau",
    "group": 1,
    "brief": "Дворянин из Прованса, публицист и скандально известный оратор. К 1789 году избран от третьего сословия и выступает за представительство, реформы и ограничение произвола двора. Родился в 1749.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/mirabeau_kventa.md",
    "html_file": "kventas-html/mirabeau.html"
  },
  {
    "id": "bailly",
    "name_ru": "Жан Сильвен Байи",
    "name_fr": "Jean Sylvain Bailly",
    "group": 1,
    "brief": "Астроном, член Французской академии, парижский учёный с репутацией честного просветителя. В 1789 году избран депутатом от Парижа. Родился в 1736.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/bailly_kventa.md",
    "html_file": "kventas-html/bailly.html"
  },
  {
    "id": "lafayette",
    "name_ru": "Маркиз де Лафайет",
    "name_fr": "Marquis de Lafayette",
    "group": 1,
    "brief": "Герой Войны за независимость США, либеральный аристократ, сторонник прав и представительства. Ищет собственный язык свободы и порядка без текстов Манон. Родился в 1757.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/lafayette_kventa.md",
    "html_file": "kventas-html/lafayette.html"
  },
  {
    "id": "sieyes",
    "name_ru": "Эмманюэль Жозеф Сийес",
    "name_fr": "Emmanuel Joseph Sieyès",
    "group": 1,
    "brief": "Аббат и политический публицист, автор памфлета «Что такое третье сословие?». В начале 1789 года формулирует язык требований третьего сословия. Родился в 1748.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/sieyes_kventa.md",
    "html_file": "kventas-html/sieyes.html"
  },
  {
    "id": "necker",
    "name_ru": "Жак Неккер",
    "name_fr": "Jacques Necker",
    "group": 1,
    "brief": "Банкир, министр финансов Людовика XVI, швейцарский протестант. Его имя связано с кредитом государства, публичной отчётностью и надеждой на финансовую реформу. Родился в 1732.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/necker_kventa.md",
    "html_file": "kventas-html/necker.html"
  },
  {
    "id": "barnave",
    "name_ru": "Антуан Барнав",
    "name_fr": "Antoine Barnave",
    "group": 1,
    "brief": "Молодой адвокат из Гренобля, участник дофинейского политического движения и сторонник представительства третьего сословия. Блестящий оратор с провинциальной репутацией. Родился в 1761.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/barnave_kventa.md",
    "html_file": "kventas-html/barnave.html"
  },
  {
    "id": "louis_xvi",
    "name_ru": "Людовик XVI",
    "name_fr": "Louis XVI",
    "group": 1,
    "brief": "Король Франции, правящий в условиях долгового, налогового и хлебного кризиса. Созывает Генеральные штаты и пытается удержать монархию в момент распада доверия. Родился в 1754.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/louis_xvi_kventa.md",
    "html_file": "kventas-html/louis_xvi.html"
  },
  {
    "id": "marat",
    "name_ru": "Жан Поль Марат",
    "name_fr": "Jean-Paul Marat",
    "group": 1,
    "brief": "Врач, учёный и публицист, много лет добивающийся признания и спорящий с академическими кругами. К 1789 году готовит политические тексты и ищет прямой разговор с народом. Родился в 1743.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/marat_kventa.md",
    "html_file": "kventas-html/marat.html"
  },
  {
    "id": "robespierre",
    "name_ru": "Максимилиан Робеспьер",
    "name_fr": "Maximilien de Robespierre",
    "group": 1,
    "brief": "Адвокат из Арраса, избранный депутатом третьего сословия. Защитник равного суда, гражданских прав и народного суверенитета. Родился в 1758.",
    "group_label": "Исторические: группа 1",
    "file": "kventas/historical/group_1/robespierre_kventa.md",
    "html_file": "kventas-html/robespierre.html"
  },
  {
    "id": "brissot",
    "name_ru": "Жак Пьер Бриссо",
    "name_fr": "Jacques Pierre Brissot",
    "group": 2,
    "brief": "Журналист, публицист и участник аболиционистских кругов, сторонник реформ и политической печати. Избран в Собрание и соединяет депутатскую трибуну с газетой. Родился в 1754.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/brissot_kventa.md",
    "html_file": "kventas-html/brissot.html"
  },
  {
    "id": "roland",
    "name_ru": "Жан Мари Ролан де ла Платьер",
    "name_fr": "Jean-Marie Roland de la Platière",
    "group": 2,
    "brief": "Королевский инспектор мануфактур, администратор и депутат Учредительного собрания. Манон рядом с его салоном, но её политические тексты идут Бертье. Родился в 1734.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/roland_kventa.md",
    "html_file": "kventas-html/roland.html"
  },
  {
    "id": "manon_roland",
    "name_ru": "Манон Ролан",
    "name_fr": "Marie-Jeanne Roland",
    "group": 2,
    "brief": "Образованная хозяйка литературно-политического круга. Пишет политические тексты для Бертье и ищет язык гражданской добродетели. Родилась в 1754.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/manon_roland_kventa.md",
    "html_file": "kventas-html/manon_roland.html"
  },
  {
    "id": "vergniaud",
    "name_ru": "Пьер Виктюрньен Верньо",
    "name_fr": "Pierre Victurnien Vergniaud",
    "group": 2,
    "brief": "Адвокат из Бордо, известный местный оратор и человек провинциальной парламентской культуры. К 1789 году входит в среду образованных юристов, ждущих реформ. Родился в 1753.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/vergniaud_kventa.md",
    "html_file": "kventas-html/vergniaud.html"
  },
  {
    "id": "danton",
    "name_ru": "Жорж Жак Дантон",
    "name_fr": "Georges Jacques Danton",
    "group": 2,
    "brief": "Парижский адвокат, человек Кордельерского квартала, энергичный переговорщик с сильным голосом и связями в городской среде. Родился в 1759.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/danton_kventa.md",
    "html_file": "kventas-html/danton.html"
  },
  {
    "id": "charlotte_corday",
    "name_ru": "Шарлотта Корде",
    "name_fr": "Charlotte Corday",
    "group": 2,
    "brief": "Молодая дворянка из Нормандии, воспитанная в монастыре. К 1789 году живёт в провинциальном мире, где новости о столице приходят через книги, письма и разговоры. Родилась в 1768.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/charlotte_corday_kventa.md",
    "html_file": "kventas-html/charlotte_corday.html"
  },
  {
    "id": "saint_just",
    "name_ru": "Луи Антуан Сен-Жюст",
    "name_fr": "Louis Antoine de Saint-Just",
    "group": 2,
    "brief": "Молодой провинциал из Блеранкура, читает античных авторов, пишет и ищет собственный политический язык. В 1789 году ему чуть больше двадцати. Родился в 1767.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/saint_just_kventa.md",
    "html_file": "kventas-html/saint_just.html"
  },
  {
    "id": "dumouriez",
    "name_ru": "Шарль Франсуа Дюмурье",
    "name_fr": "Charles François Dumouriez",
    "group": 2,
    "brief": "Опытный офицер и дипломат старой монархии, прошедший войну и тайные поручения. К 1789 году ищет роль в меняющейся Франции. Родился в 1739.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/dumouriez_kventa.md",
    "html_file": "kventas-html/dumouriez.html"
  },
  {
    "id": "hebert",
    "name_ru": "Жак-Рене Эбер",
    "name_fr": "Jacques-René Hébert",
    "group": 2,
    "brief": "Парижский человек пера и театральной среды, привыкший к бедности, сатире и резкому языку улицы. К 1789 году ищет способ пробиться через печать. Родился в 1757.",
    "group_label": "Исторические: группа 2",
    "file": "kventas/historical/group_2/hebert_kventa.md",
    "html_file": "kventas-html/hebert.html"
  },
  {
    "id": "couthon",
    "name_ru": "Жорж Кутон",
    "name_fr": "Georges Couthon",
    "group": 3,
    "brief": "Адвокат из Оверни, человек провинциальных юридических кругов, живущий с тяжёлой болезнью и ограниченной подвижностью. К 1789 году внимательно следит за реформами. Родился в 1755.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/couthon_kventa.md",
    "html_file": "kventas-html/couthon.html"
  },
  {
    "id": "desmoulins",
    "name_ru": "Камиль Демулен",
    "name_fr": "Camille Desmoulins",
    "group": 3,
    "brief": "Молодой адвокат и публицист, выпускник коллежа Людовика Великого, знакомый с Робеспьером ещё по учёбе. К 1789 году живёт в Париже и ищет голос в политике. Родился в 1760.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/desmoulins_kventa.md",
    "html_file": "kventas-html/desmoulins.html"
  },
  {
    "id": "carnot",
    "name_ru": "Лазар Карно",
    "name_fr": "Lazare Carnot",
    "group": 3,
    "brief": "Военный инженер, офицер и математик, воспитанный на дисциплине, фортификации и просветительской рациональности. Родился в 1753.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/carnot_kventa.md",
    "html_file": "kventas-html/carnot.html"
  },
  {
    "id": "barere",
    "name_ru": "Бертран Барер",
    "name_fr": "Bertrand Barère",
    "group": 3,
    "brief": "Юрист и литератор из Тарба, человек провинциальной судебной и академической среды. К 1789 году входит в политику через язык реформ и представительства. Родился в 1755.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/barere_kventa.md",
    "html_file": "kventas-html/barere.html"
  },
  {
    "id": "fouquier_tinville",
    "name_ru": "Антуан Фукье-Тенвиль",
    "name_fr": "Antoine Quentin Fouquier-Tinville",
    "group": 3,
    "brief": "Пикардийский юрист, работавший в судебной системе Старого порядка. К 1789 году несёт опыт канцелярий, долгов и зависимостей. Родился в 1746.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/fouquier_tinville_kventa.md",
    "html_file": "kventas-html/fouquier_tinville.html"
  },
  {
    "id": "carrier",
    "name_ru": "Жан-Батист Каррье",
    "name_fr": "Jean-Baptiste Carrier",
    "group": 3,
    "brief": "Провинциальный адвокат из Орийака, представитель образованного третьего сословия. К 1789 году входит в политику через местные собрания и жалобы. Родился в 1756.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/carrier_kventa.md",
    "html_file": "kventas-html/carrier.html"
  },
  {
    "id": "fouche",
    "name_ru": "Жозеф Фуше",
    "name_fr": "Joseph Fouché",
    "group": 3,
    "brief": "Бывший ораторианец, преподаватель и человек строгой школьной дисциплины. К 1789 году живёт в среде образования, науки и церковных порядков. Родился в 1759.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/fouche_kventa.md",
    "html_file": "kventas-html/fouche.html"
  },
  {
    "id": "barras",
    "name_ru": "Поль Баррас",
    "name_fr": "Paul Barras",
    "group": 3,
    "brief": "Дворянин из Прованса, бывший офицер, привыкший к военной службе, долгам и салонным связям. К 1789 году ищет место в новой политической ситуации. Родился в 1755.",
    "group_label": "Исторические: группа 3",
    "file": "kventas/historical/group_3/barras_kventa.md",
    "html_file": "kventas-html/barras.html"
  },
  {
    "id": "tallien",
    "name_ru": "Жан-Ламбер Тальен",
    "name_fr": "Jean-Lambert Tallien",
    "group": 4,
    "brief": "Молодой парижский человек печати, сын управляющего, связанный с типографской и газетной средой. К 1789 году только входит в мир публичного слова и политики. Родился в 1767.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/tallien_kventa.md",
    "html_file": "kventas-html/tallien.html"
  },
  {
    "id": "napoleon",
    "name_ru": "Наполеон Бонапарт",
    "name_fr": "Napoléon Bonaparte",
    "group": 4,
    "brief": "Молодой артиллерийский офицер с Корсики, выпускник Бриеннской школы и Парижской военной школы. В 1789 году служит во французской армии. Родился в 1769.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/napoleon_kventa.md",
    "html_file": "kventas-html/napoleon.html"
  },
  {
    "id": "talleyrand",
    "name_ru": "Шарль Морис де Талейран",
    "name_fr": "Charles Maurice de Talleyrand-Périgord",
    "group": 4,
    "brief": "Епископ Отёнский, аристократ и дипломатичный церковный политик. К 1789 году готов участвовать в Генеральных штатах от духовенства. Родился в 1754.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/talleyrand_kventa.md",
    "html_file": "kventas-html/talleyrand.html"
  },
  {
    "id": "babeuf",
    "name_ru": "Гракх Бабёф",
    "name_fr": "François-Noël Babeuf",
    "group": 4,
    "brief": "Пикардийский землемер и писарь, работающий с феодальными правами, налогами и земельными архивами. К 1789 году хорошо знает деревенские жалобы. Родился в 1760.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/babeuf_kventa.md",
    "html_file": "kventas-html/babeuf.html"
  },
  {
    "id": "buonarroti",
    "name_ru": "Филиппо Буонарроти",
    "name_fr": "Filippo Buonarroti",
    "group": 4,
    "brief": "Итальянский дворянин и публицист из Тосканы, сторонник просветительских идей и реформ. К 1789 году смотрит на Францию как на политическую лабораторию. Родился в 1761.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/buonarroti_kventa.md",
    "html_file": "kventas-html/buonarroti.html"
  },
  {
    "id": "pichegru",
    "name_ru": "Жан-Шарль Пишегрю",
    "name_fr": "Jean-Charles Pichegru",
    "group": 4,
    "brief": "Офицер-артиллерист и преподаватель математики, вышедший из скромной семьи Франш-Конте. К 1789 году служит в армии Старого порядка. Родился в 1761.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/pichegru_kventa.md",
    "html_file": "kventas-html/pichegru.html"
  },
  {
    "id": "moreau",
    "name_ru": "Жан Виктор Моро",
    "name_fr": "Jean Victor Marie Moreau",
    "group": 4,
    "brief": "Молодой юрист из Бретани и организатор студенческой среды в Ренне. К 1789 году находится рядом с провинциальным политическим кипением. Родился в 1763.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/moreau_kventa.md",
    "html_file": "kventas-html/moreau.html"
  },
  {
    "id": "larevelliere",
    "name_ru": "Луи-Мари де Ларевельер-Лепо",
    "name_fr": "Louis-Marie de La Révellière-Lépeaux",
    "group": 4,
    "brief": "Анжуйский юрист и человек просветительских кругов, враждебный церковным привилегиям. К 1789 году входит в провинциальную политику. Родился в 1753.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/larevelliere_kventa.md",
    "html_file": "kventas-html/larevelliere.html"
  },
  {
    "id": "jourdan",
    "name_ru": "Жан-Батист Журдан",
    "name_fr": "Jean-Baptiste Jourdan",
    "group": 4,
    "brief": "Бывший солдат королевской армии, ветеран американской войны, живущий торговлей и ремеслом в Лиможе. Родился в 1762.",
    "group_label": "Исторические: группа 4",
    "file": "kventas/historical/group_4/jourdan_kventa.md",
    "html_file": "kventas-html/jourdan.html"
  },
  {
    "id": "boulanger",
    "name_ru": "Пьер Моро, булочник",
    "name_fr": "Pierre Moreau, boulanger",
    "group": 5,
    "type": "citizen",
    "brief": "Булочник с рынка Ле-Аль. Покупает муку, печёт хлеб, устанавливает цены и первым чувствует опасность хлебного бунта. Вымышленный типаж, около 45 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/boulanger_kventa.md",
    "html_file": "kventas-html/boulanger.html"
  },
  {
    "id": "poissarde",
    "name_ru": "Мари-Жанна Дюваль, торговка",
    "name_fr": "Marie-Jeanne Duval, poissarde",
    "group": 5,
    "type": "citizen",
    "brief": "Торговка рыбой на рынке Ле-Аль. Знает всех, говорит громче всех и живёт внутри рыночной политики Парижа. Вымышленный типаж, около 40 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/poissarde_kventa.md",
    "html_file": "kventas-html/poissarde.html"
  },
  {
    "id": "vinier",
    "name_ru": "Жак Бертье, откупщик",
    "name_fr": "Jacques Berthier, fermier d'octroi",
    "group": 5,
    "type": "citizen",
    "brief": "Откупщик у заставы Сен-Мартен, человек Генерального откупа и налоговой стены. Защищает октруа как доход казны и получает тексты Манон для Бертье.",
    "group_label": "Горожане",
    "file": "kventas/citizens/vinier_kventa.md",
    "html_file": "kventas-html/vinier.html"
  },
  {
    "id": "menuisier",
    "name_ru": "Антуан Ревельон, мастер-столяр",
    "name_fr": "Antoine Réveillon, maître menuisier",
    "group": 5,
    "type": "citizen",
    "brief": "Цеховой мастер-столяр из предместья Сент-Антуан. У него подмастерья, мастерская, репутация и страх перед ценами на хлеб. Вымышленный типаж, около 48 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/menuisier_kventa.md",
    "html_file": "kventas-html/menuisier.html"
  },
  {
    "id": "imprimeur",
    "name_ru": "Луи Прюдом, типограф",
    "name_fr": "Louis Prudhomme, imprimeur",
    "group": 5,
    "type": "citizen",
    "brief": "Типограф в Латинском квартале. Печатает памфлеты, листовки и газеты, узнавая новости раньше города. Вымышленный типаж, около 35 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/imprimeur_kventa.md",
    "html_file": "kventas-html/imprimeur.html"
  },
  {
    "id": "lavandiere",
    "name_ru": "Катрин Лебон, прачка",
    "name_fr": "Catherine Lebon, lavandière",
    "group": 5,
    "type": "citizen",
    "brief": "Прачка на берегу Сены, вдова с двумя детьми. Тяжёлый труд, долги и женская солидарность держат её в городской сети слухов. Вымышленный типаж, около 32 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/lavandiere_kventa.md",
    "html_file": "kventas-html/lavandiere.html"
  },
  {
    "id": "cafetier",
    "name_ru": "Франсуа Прокоп, хозяин кафе",
    "name_fr": "François Procope, cafetier",
    "group": 5,
    "type": "citizen",
    "brief": "Хозяин кафе в Пале-Рояль. Его зал собирает разговоры, слухи, памфлеты и людей, которые спорят о будущем Франции. Вымышленный типаж, около 42 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/cafetier_kventa.md",
    "html_file": "kventas-html/cafetier.html"
  },
  {
    "id": "mercier",
    "name_ru": "Этьен Дюпон, лавочник",
    "name_fr": "Étienne Dupont, mercier",
    "group": 5,
    "type": "citizen",
    "brief": "Лавочник-галантерейщик на рю Сент-Оноре. Платит налоги, читает газеты, хочет порядка и представительства. Вымышленный типаж, около 38 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/mercier_kventa.md",
    "html_file": "kventas-html/mercier.html"
  },
  {
    "id": "actrice",
    "name_ru": "Жюли Ренар, актриса",
    "name_fr": "Julie Renard, actrice",
    "group": 5,
    "type": "citizen",
    "brief": "Актриса Комеди-Франсез. Театр для неё — зеркало политики, цензуры, репутации и городской публики. Вымышленный типаж, около 28 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/actrice_kventa.md",
    "html_file": "kventas-html/actrice.html"
  },
  {
    "id": "avocat",
    "name_ru": "Шарль Меренвиль, адвокат",
    "name_fr": "Charles Mérinville, avocat",
    "group": 5,
    "type": "citizen",
    "brief": "Адвокат при Парижском парламенте. Знает законы, ненавидит привилегии, читает Руссо и Монтескьё. Вымышленный типаж, около 33 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/avocat_kventa.md",
    "html_file": "kventas-html/avocat.html"
  },
  {
    "id": "cure",
    "name_ru": "Отец Жером Тиссо, кюре",
    "name_fr": "Père Jérôme Tissot, curé",
    "group": 5,
    "type": "citizen",
    "brief": "Приходской священник церкви Сент-Этьен-дю-Мон. Бедный кюре ближе к народу, чем к епископам, и видит голод через приходские книги. Вымышленный типаж, около 55 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/cure_kventa.md",
    "html_file": "kventas-html/cure.html"
  },
  {
    "id": "chirurgien",
    "name_ru": "Никола Гранже, хирург",
    "name_fr": "Nicolas Grangé, chirurgien",
    "group": 5,
    "type": "citizen",
    "brief": "Хирург при больнице Отель-Дьё. Практик, каждый день видящий болезни бедности, переполненные палаты и цену хлеба в телах людей. Вымышленный типаж, около 40 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/chirurgien_kventa.md",
    "html_file": "kventas-html/chirurgien.html"
  },
  {
    "id": "invalide",
    "name_ru": "Жан-Батист Лакруа, солдат-инвалид",
    "name_fr": "Jean-Baptiste Lacroix, invalide",
    "group": 5,
    "type": "citizen",
    "brief": "Ветеран, живущий при Доме инвалидов. Воевал в Семилетней войне, знает армию изнутри и помнит, где хранится оружие. Вымышленный типаж, около 58 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/invalide_kventa.md",
    "html_file": "kventas-html/invalide.html"
  },
  {
    "id": "journalier",
    "name_ru": "Пьер Ламбер, подёнщик",
    "name_fr": "Pierre Lambert, journalier",
    "group": 5,
    "type": "citizen",
    "brief": "Подёнщик-строитель без цеха, защиты и постоянной работы. Первый голодает при кризисе и первым ищет заработок на улице. Вымышленный типаж, около 25 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/journalier_kventa.md",
    "html_file": "kventas-html/journalier.html"
  },
  {
    "id": "servante",
    "name_ru": "Мадлен Флёри, служанка",
    "name_fr": "Madeleine Fleury, servante",
    "group": 5,
    "type": "citizen",
    "brief": "Горничная в дворянском особняке в Маре. Видит жизнь аристократии изнутри, слышит разговоры хозяев и носит городские слухи. Вымышленный типаж, около 22 лет.",
    "group_label": "Горожане",
    "file": "kventas/citizens/servante_kventa.md",
    "html_file": "kventas-html/servante.html"
  },
  {
    "id": "marie_antoinette",
    "name_ru": "Мария-Антуанетта",
    "name_fr": "Marie-Antoinette d'Autriche",
    "group": 6,
    "type": "royalist",
    "brief": "Королева Франции, жена Людовика XVI, дочь австрийской императрицы Марии-Терезии. К 1789 году окружена придворной враждой, слухами и образом «Австриячки». Родилась в 1755.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/marie_antoinette_kventa.md",
    "html_file": "kventas-html/marie_antoinette.html"
  },
  {
    "id": "artois",
    "name_ru": "Граф д'Артуа",
    "name_fr": "Charles Philippe, comte d'Artois",
    "group": 6,
    "type": "royalist",
    "brief": "Младший брат Людовика XVI, ультра-роялистический принц двора. К 1789 году связан с партией сопротивления реформам и защитой дворянских привилегий. Родился в 1757.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/artois_kventa.md",
    "html_file": "kventas-html/artois.html"
  },
  {
    "id": "provence",
    "name_ru": "Граф Прованский",
    "name_fr": "Louis Stanislas Xavier, comte de Provence",
    "group": 6,
    "type": "royalist",
    "brief": "Средний брат Людовика XVI, умный и осторожный придворный политик. К 1789 году маневрирует между двором, репутацией и собственными амбициями. Родился в 1755.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/provence_kventa.md",
    "html_file": "kventas-html/provence.html"
  },
  {
    "id": "maury",
    "name_ru": "Аббат Мори",
    "name_fr": "Jean-Sifrein Maury",
    "group": 6,
    "type": "royalist",
    "brief": "Аббат, проповедник и блестящий оратор, сын сапожника, поднявшийся талантом. К 1789 году защищает церковь и сословный порядок. Родился в 1746.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/maury_kventa.md",
    "html_file": "kventas-html/maury.html"
  },
  {
    "id": "cazales",
    "name_ru": "Жак Антуан Мари де Казалес",
    "name_fr": "Jacques Antoine Marie de Cazalès",
    "group": 6,
    "type": "royalist",
    "brief": "Дворянин из Тулузы, офицер-драгун и сильный полемист дворянской среды. К 1789 году готов защищать честь сословия и монархический порядок. Родился в 1758.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/cazales_kventa.md",
    "html_file": "kventas-html/cazales.html"
  },
  {
    "id": "breteuil",
    "name_ru": "Барон де Бретёй",
    "name_fr": "Louis Auguste Le Tonnelier, baron de Breteuil",
    "group": 6,
    "type": "royalist",
    "brief": "Министр королевского дома, дипломат и сторонник жёсткой линии двора. К 1789 году принадлежит к кругу людей, готовых отвечать на кризис силой и приказом. Родился в 1730.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/breteuil_kventa.md",
    "html_file": "kventas-html/breteuil.html"
  },
  {
    "id": "bouille",
    "name_ru": "Маркиз де Буйе",
    "name_fr": "François Claude Amour, marquis de Bouillé",
    "group": 6,
    "type": "royalist",
    "brief": "Генерал, командующий войсками на восточной границе, дисциплинарный военный старой школы. Верен королю и армии. Родился в 1739.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/bouille_kventa.md",
    "html_file": "kventas-html/bouille.html"
  },
  {
    "id": "polignac",
    "name_ru": "Герцогиня де Полиньяк",
    "name_fr": "Yolande de Polastron, duchesse de Polignac",
    "group": 6,
    "type": "royalist",
    "brief": "Ближайшая фаворитка Марии-Антуанетты, гувернантка королевских детей. Символ придворных излишеств и фаворитизма при Версале. Родилась в 1749.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/polignac_kventa.md",
    "html_file": "kventas-html/polignac.html"
  },
  {
    "id": "lamballe",
    "name_ru": "Принцесса де Ламбаль",
    "name_fr": "Marie Thérèse Louise de Savoie-Carignan, princesse de Lamballe",
    "group": 6,
    "type": "royalist",
    "brief": "Подруга королевы, суперинтендант двора. Итальянского происхождения, вдова, связанная с внутренним кругом Марии-Антуанетты. Родилась в 1749.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/lamballe_kventa.md",
    "html_file": "kventas-html/lamballe.html"
  },
  {
    "id": "fersen",
    "name_ru": "Аксель фон Ферзен",
    "name_fr": "Axel von Fersen",
    "group": 6,
    "type": "royalist",
    "brief": "Шведский граф, офицер на французской службе, участник Войны за независимость США. Близок к королеве и придворной дипломатии. Родился в 1755.",
    "group_label": "Роялисты",
    "file": "kventas/royalists/fersen_kventa.md",
    "html_file": "kventas-html/fersen.html"
  }
];
