window.REVOLUTION_ECONOMY_DATA = {
  roles: [
    {
      id: "day_laborer",
      title: "Поденщик / грузчик",
      group: "городские низы",
      color: "#1f6f78",
      why: "Нижний край экономики: дневная работа, семья, почти нет запаса.",
      incomeName: "дневная плата",
      baseIncome: 5,
      mouths: 2,
      fixedCost: 1,
      professionCost: 0,
      statusCost: 0,
      startCash: 0,
      creditLimit: 2,
      workSensitivity: 1.2,
      demandSensitivity: 0.1,
      supplySensitivity: 0,
      assignatExposure: 0.8,
      foodRelief: 0,
      stressMove: "занять у соседа или искать покровителя",
      crisisMove: "идти в секцию, толкать жалобу о хлебе",
      surplusMove: "выплатить долг или купить еду семье",
      stressImpact: { debt: 1, street: 1 },
      crisisImpact: { street: 2, politicization: 1 }
    },
    {
      id: "washerwoman",
      title: "Прачка / служанка",
      group: "женский городской труд",
      color: "#a84d6f",
      why: "Зависит от нанимателей и цены хлеба; быстро превращает частную нужду в просьбу или рынок.",
      incomeName: "плата за труд",
      baseIncome: 5,
      mouths: 1.5,
      fixedCost: 1.5,
      professionCost: 0.5,
      statusCost: 0,
      startCash: 0,
      creditLimit: 2,
      workSensitivity: 0.9,
      demandSensitivity: 0.2,
      supplySensitivity: 0,
      assignatExposure: 0.7,
      foodRelief: 0,
      stressMove: "просить хлеб в долг или искать вторую работу",
      crisisMove: "идти на рынок и в марш за хлебом",
      surplusMove: "погасить мелкий долг",
      stressImpact: { debt: 1, street: 1 },
      crisisImpact: { street: 2, politicization: 1 }
    },
    {
      id: "market_woman",
      title: "Рыночная торговка",
      group: "рынок и улица",
      color: "#a33d2e",
      why: "Связывает цены, очереди, слухи и коллективное действие.",
      incomeName: "рыночная выручка",
      baseIncome: 6,
      mouths: 2,
      fixedCost: 1,
      professionCost: 1,
      statusCost: 0,
      startCash: 1,
      creditLimit: 3,
      workSensitivity: 0.2,
      demandSensitivity: 0.8,
      supplySensitivity: 0.7,
      assignatExposure: 0.4,
      foodRelief: 0,
      stressMove: "поднять цену или искать обходной товар",
      crisisMove: "обвинить поставщиков и вести рынок к маршу",
      surplusMove: "купить запас для перепродажи",
      stressImpact: { suspicion: 1, blackMarket: 1 },
      crisisImpact: { street: 2, suspicion: 1 }
    },
    {
      id: "artisan_master",
      title: "Ремесленник-мастер",
      group: "мастерская",
      color: "#205b8f",
      why: "Проверяет заказы, мастерскую, содержание работников и падение спроса.",
      incomeName: "заказы мастерской",
      baseIncome: 8,
      mouths: 2,
      fixedCost: 2,
      professionCost: 2,
      statusCost: 0.5,
      startCash: 1,
      creditLimit: 5,
      workSensitivity: 0.6,
      demandSensitivity: 1,
      supplySensitivity: 0.2,
      assignatExposure: 0.5,
      foodRelief: 0,
      stressMove: "сократить подмастерья или взять политический заказ",
      crisisMove: "закрыть мастерскую и идти за защитой в секцию",
      surplusMove: "купить материал или нанять подмастерье",
      stressImpact: { unemployment: 1, street: 1 },
      crisisImpact: { street: 1, politicization: 1, unemployment: 1 }
    },
    {
      id: "journeyman",
      title: "Подмастерье",
      group: "наемный труд мастерской",
      color: "#2f7d7e",
      why: "Стоит между мастером и улицей: зарплата падает раньше, чем исчезают долги хозяина.",
      incomeName: "жалованье",
      baseIncome: 5,
      mouths: 1.5,
      fixedCost: 1,
      professionCost: 0.5,
      statusCost: 0,
      startCash: 0,
      creditLimit: 2,
      workSensitivity: 1.1,
      demandSensitivity: 0.3,
      supplySensitivity: 0.1,
      assignatExposure: 0.8,
      foodRelief: 0,
      stressMove: "требовать плату или искать другую мастерскую",
      crisisMove: "вступить в секцию или бунтовать против хозяина",
      surplusMove: "копить на инструмент",
      stressImpact: { street: 1, unemployment: 1 },
      crisisImpact: { street: 2, politicization: 1 }
    },
    {
      id: "baker",
      title: "Булочник",
      group: "хлебная точка",
      color: "#9b6a1a",
      why: "Центр подозрения: мука дорожает, очередь требует хлеб по терпимой цене.",
      incomeName: "продажа хлеба",
      baseIncome: 9,
      mouths: 2,
      fixedCost: 2,
      professionCost: 2.5,
      statusCost: 0,
      startCash: 1,
      creditLimit: 4,
      workSensitivity: 0.1,
      demandSensitivity: 0.7,
      supplySensitivity: 1.1,
      assignatExposure: 0.5,
      foodRelief: 0.5,
      stressMove: "сократить продажу или просить муку у муниципалитета",
      crisisMove: "прятать муку, закрывать лавку, становиться мишенью толпы",
      surplusMove: "купить муку вперед",
      stressImpact: { suspicion: 2 },
      crisisImpact: { suspicion: 3, street: 1, blackMarket: 1 }
    },
    {
      id: "shopkeeper",
      title: "Лавочник / трактирщик",
      group: "запас и кредит соседям",
      color: "#517648",
      why: "Имеет запас, слышит слухи, дает в долг и легко становится спекулянтом в глазах улицы.",
      incomeName: "оборот лавки",
      baseIncome: 8,
      mouths: 2,
      fixedCost: 2,
      professionCost: 1.5,
      statusCost: 0.5,
      startCash: 2,
      creditLimit: 5,
      workSensitivity: 0.1,
      demandSensitivity: 0.8,
      supplySensitivity: 0.8,
      assignatExposure: 0.5,
      foodRelief: 0,
      stressMove: "поднять цену, урезать кредит соседям или спрятать запас",
      crisisMove: "уйти в черный рынок или искать защиту секции",
      surplusMove: "расширить запас",
      stressImpact: { suspicion: 1, blackMarket: 1 },
      crisisImpact: { suspicion: 2, blackMarket: 2 }
    },
    {
      id: "printer",
      title: "Типограф / памфлетист",
      group: "политический язык",
      color: "#a84d6f",
      why: "Превращает экономическую боль в обвинение, петицию и политический текст.",
      incomeName: "печать",
      baseIncome: 8,
      mouths: 2,
      fixedCost: 2,
      professionCost: 2,
      statusCost: 0.5,
      startCash: 1,
      creditLimit: 5,
      workSensitivity: 0.3,
      demandSensitivity: 0.6,
      supplySensitivity: 0.3,
      assignatExposure: 0.6,
      foodRelief: 0,
      stressMove: "брать рискованный памфлетный заказ",
      crisisMove: "печатать обвинение без адреса типографии",
      surplusMove: "купить бумагу и шрифт",
      stressImpact: { politicization: 1, suspicion: 1 },
      crisisImpact: { politicization: 2, suspicion: 1 }
    },
    {
      id: "lawyer_deputy",
      title: "Адвокат / депутат третьего",
      group: "представительство",
      color: "#205b8f",
      why: "Связывает жалобы, петиции, процедуру и декреты.",
      incomeName: "гонорары и политические поручения",
      baseIncome: 7,
      mouths: 2,
      fixedCost: 2,
      professionCost: 1,
      statusCost: 1,
      startCash: 1,
      creditLimit: 6,
      workSensitivity: 0.2,
      demandSensitivity: 0.4,
      supplySensitivity: 0,
      assignatExposure: 0.5,
      foodRelief: 0,
      stressMove: "искать патрона или монетизировать петиции",
      crisisMove: "радикализировать речь и требовать декрета",
      surplusMove: "финансировать клуб или кампанию",
      stressImpact: { politicization: 1 },
      crisisImpact: { politicization: 2, street: 1 }
    },
    {
      id: "banker",
      title: "Банкир / крупный буржуа",
      group: "капитал и кредит",
      color: "#3f424a",
      why: "Показывает, что кризис не всех беднит одинаково: кто-то покупает долги, влияние и имущество.",
      incomeName: "проценты, сделки, кредит",
      baseIncome: 14,
      mouths: 3,
      fixedCost: 3,
      professionCost: 1,
      statusCost: 3,
      startCash: 4,
      creditLimit: 12,
      workSensitivity: 0.05,
      demandSensitivity: 0.3,
      supplySensitivity: 0,
      assignatExposure: 0.2,
      foodRelief: 0,
      stressMove: "прятать капитал или требовать гарантий",
      crisisMove: "выводить деньги и искать политическую защиту",
      surplusMove: "дать заем, купить имущество или зависимость",
      stressImpact: { eliteFear: 1 },
      crisisImpact: { eliteFear: 2, suspicion: 1 },
      surplusImpact: { debtDependency: 1, eliteConfidence: 1 }
    }
  ],
  policies: {
    none: {
      label: "Без решения",
      description: "Игроки ничего системного не меняют: кризис доедает слабых и поднимает уличное давление.",
      effects: {}
    },
    subsidy: {
      label: "Муниципальная субсидия хлеба",
      description: "Город гасит цену для потребителей, но прожигает фонд и усиливает зависимость от власти.",
      effects: { consumerBreadRelief: 1, municipalFund: -3, street: -1, debtDependency: 1 }
    },
    maximum: {
      label: "Максимум цен",
      description: "Цена на бумаге падает, но торговцы и булочники теряют стимул показывать товар.",
      effects: { breadCap: 3, traderIncomePenalty: -1.2, street: -1, suspicion: 1, blackMarket: 2, supply: -0.1 }
    },
    free_market: {
      label: "Свободный рынок зерна",
      description: "Торговцам выгоднее везти товар, но городская беднота воспринимает это как отказ от защиты.",
      effects: { breadShift: 0.8, traderIncomeBonus: 1.4, supply: 0.12, street: 1, suspicion: 1 }
    },
    requisition: {
      label: "Реквизиции и принудительный подвоз",
      description: "Город получает хлеб, но растут грубость контроля и сопротивление вокруг снабжения.",
      effects: { consumerBreadRelief: 0.6, supply: 0.18, street: -0.5, suspicion: 1, blackMarket: 1, provinceAnger: 2 }
    },
    assignats: {
      label: "Эмиссия ассигнатов",
      description: "Ликвидность появляется сейчас, покупательная способность падает следом.",
      effects: { incomeBonus: 0.8, assignatRateShift: -0.12, debtDependency: 1, suspicion: 0.5 }
    }
  },
  scenarios: {
    baseline_1789: {
      label: "Париж 1789: хлеб дорожает",
      note: "Базовый стенд: напряжение растет, но системное решение появляется только в 4 такте.",
      turns: [
        { label: "Такт 1", bread: 2, work: 1, demand: 1, supply: 1, assignatRate: 1, suspicion: 0, street: 0, politicization: 0 },
        { label: "Такт 2", bread: 3, work: 0.9, demand: 0.9, supply: 0.85, assignatRate: 1, suspicion: 1, street: 1, politicization: 1 },
        { label: "Такт 3", bread: 4, work: 0.78, demand: 0.82, supply: 0.65, assignatRate: 0.95, suspicion: 2, street: 2, politicization: 2 },
        { label: "Такт 4", bread: 4.2, work: 0.8, demand: 0.85, supply: 0.7, assignatRate: 0.93, suspicion: 2, street: 3, politicization: 2 }
      ]
    },
    soft_tension: {
      label: "Мягкое напряжение",
      note: "Проверяет нижнюю границу: экономика должна напрягать бедных, но не валить всех сразу.",
      turns: [
        { label: "Такт 1", bread: 2, work: 1, demand: 1, supply: 1, assignatRate: 1, suspicion: 0, street: 0, politicization: 0 },
        { label: "Такт 2", bread: 2.5, work: 0.95, demand: 0.96, supply: 0.9, assignatRate: 1, suspicion: 0.5, street: 0.5, politicization: 0.5 },
        { label: "Такт 3", bread: 3, work: 0.92, demand: 0.92, supply: 0.82, assignatRate: 0.98, suspicion: 1, street: 1, politicization: 1 },
        { label: "Такт 4", bread: 3.2, work: 0.9, demand: 0.92, supply: 0.84, assignatRate: 0.98, suspicion: 1, street: 1.2, politicization: 1.2 }
      ]
    },
    hard_bread_shock: {
      label: "Жесткий хлебный шок",
      note: "Проверяет верхнюю границу: не превращает ли хлеб всех в одинаково мертвых должников.",
      turns: [
        { label: "Такт 1", bread: 2.5, work: 0.95, demand: 0.95, supply: 0.9, assignatRate: 1, suspicion: 0.5, street: 0.5, politicization: 0.5 },
        { label: "Такт 2", bread: 3.8, work: 0.82, demand: 0.8, supply: 0.62, assignatRate: 0.95, suspicion: 2, street: 2, politicization: 1.5 },
        { label: "Такт 3", bread: 5, work: 0.72, demand: 0.7, supply: 0.5, assignatRate: 0.9, suspicion: 3, street: 4, politicization: 3 },
        { label: "Такт 4", bread: 5.2, work: 0.7, demand: 0.72, supply: 0.55, assignatRate: 0.88, suspicion: 3.5, street: 5, politicization: 3.5 }
      ]
    },
    work_collapse: {
      label: "Падает работа и спрос",
      note: "Проверяет ремесленников, подмастерьев и городскую занятость.",
      turns: [
        { label: "Такт 1", bread: 2, work: 1, demand: 1, supply: 1, assignatRate: 1, suspicion: 0, street: 0, politicization: 0 },
        { label: "Такт 2", bread: 2.8, work: 0.75, demand: 0.75, supply: 0.84, assignatRate: 0.98, suspicion: 1, street: 1, politicization: 1 },
        { label: "Такт 3", bread: 3.6, work: 0.58, demand: 0.62, supply: 0.72, assignatRate: 0.95, suspicion: 1.5, street: 2.5, politicization: 2 },
        { label: "Такт 4", bread: 3.8, work: 0.6, demand: 0.66, supply: 0.74, assignatRate: 0.95, suspicion: 2, street: 3, politicization: 2.5 }
      ]
    }
  },
  scenarioMatrix: [
    { scenario: "baseline_1789", policy: "none" },
    { scenario: "baseline_1789", policy: "subsidy" },
    { scenario: "baseline_1789", policy: "maximum" },
    { scenario: "baseline_1789", policy: "free_market" },
    { scenario: "baseline_1789", policy: "requisition" },
    { scenario: "baseline_1789", policy: "assignats" },
    { scenario: "soft_tension", policy: "none" },
    { scenario: "soft_tension", policy: "maximum" },
    { scenario: "hard_bread_shock", policy: "subsidy" },
    { scenario: "hard_bread_shock", policy: "maximum" },
    { scenario: "hard_bread_shock", policy: "requisition" },
    { scenario: "work_collapse", policy: "subsidy" },
    { scenario: "work_collapse", policy: "assignats" },
    { scenario: "work_collapse", policy: "free_market" }
  ],
  sensitivity: [
    { id: "bread_up", label: "Цена хлеба +1", patch: { breadShiftAll: 1 } },
    { id: "bread_down", label: "Цена хлеба -0.5", patch: { breadShiftAll: -0.5 } },
    { id: "work_down", label: "Работа -20%", patch: { workShiftAll: -0.2 } },
    { id: "supply_down", label: "Снабжение -20%", patch: { supplyShiftAll: -0.2 } },
    { id: "rent_up", label: "Аренда и быт +1", patch: { fixedCostShift: 1 } },
    { id: "mouths_up", label: "Иждивенцы +0.5", patch: { mouthsShift: 0.5 } },
    { id: "credit_tight", label: "Кредит урезан вдвое", patch: { creditMultiplier: 0.5 } },
    { id: "assignat_down", label: "Ассигнат -15%", patch: { assignatRateShiftAll: -0.15 } }
  ]
};
